- src/test/java/school/redrover/FirstTest.java
> refactor_test

- src/test/java/school/redrover/GroupCarlTheFogTest.java
> sleep value change

- src/test/java/school/redrover/FirstTest.java
> New refactoring 'sleep(900)'

- src/test/java/school/redrover/GroupQaClimbersTest.java
fixed locator in testTextBox test
> add testAllElementsOnFirstPage test

- src/test/java/school/redrover/ildanaTest.java
> add IldanaTest class

- src/test/java/school/redrover/GroupQaClimbersTest.java
testClickOnHomeCheckBox is added
> add testClickOnHomeCheckBox

- src/test/java/school/redrover/GroupIntroVertsQaTest.java
https://parabank.parasoft.com/parabank/index.htm
> registrTest2.0

- src/test/java/school/redrover/GroupCarlTheFogTest.java
> GroupCarlTheFogTestregisterNowDisplayTest

- src/test/java/school/redrover/GroupSurvivorsTest.java
Class GroupSurvivorsTest added
> evgenySSearchTest added

- src/test/java/school/redrover/LocomotiveGroupTest.java
Serghei condrasov completed first test, please check
> Serghei Condrasov (LocomotiveGroupTest)

- src/test/java/ArturSabanadzeTest.java
Check the website title.
Check the input form.
Check the disabled input form.
> My first test which have 3 functions:

- src/test/java/school/redrover/GroupIntroVertsQaTest.java
add testCorrectLogin
https://parabank.parasoft.com/parabank/index.htm
> refactor test public void testRegistr

- src/test/java/school/redrover/GroupForwardTest.java
URL is placed in a variable, driver.quit() moved to 'finally'; test logoIsDisplayed added to the GroupForwardTest
> Class GroupForwardTest refactoring

- src/test/java/school/redrover/filipRahuliaDraftTest.java
My first commit, don't be strict
> hw_17 - first commit

- src/test/java/school/redrover/filipRahuliaDraftTest.java
> hw_17 - added 'try' construction

- src/test/java/school/redrover/GroupUnicornsTest.java
Could you please review my Test and approve my PR?
Thank you.
> add Batina's first test

- src/test/java/school/redrover/GroupAqaLearnTest.java
> add first test

- src/test/java/school/redrover/GroupUnicornsTest.java
Hi guys! Please, review, comment, and approve my PR.
Thanks in advance!
> add my second test

- src/test/java/school/redrover/GroupQaClimbersTest.java
> FirstCommitdenistaranchik

- src/test/java/school/redrover/GroupQaClimbersTest.java
test testListOfAlertsFrameAndWindows refactored, test testBookStoreAplication added
> Refactoring and new test

- src/test/java/school/redrover/GroupUnicornsTest.java
> testComputersMenu

- src/test/java/school/redrover/GroupJavaExplorersTest.java
> Add invalidLoginTestWithUnExistedUser test

- src/test/java/school/redrover/GroupIntroVertsQaTest.java
Test of Text-Box 'name' from DEMOQA
> First test from AkiMira

- src/test/java/school/redrover/AbramovTest.java
> First commit

- src/test/java/school/redrover/KuzminaTest.java
Created 1 test with two checks that titles of pages as expected. Test was passed.
> Sk task17 site opened test

- src/test/java/school/redrover/GroupUnitedByJavaTest.java
testClickElementsLinkText_status_201
> testClickElementsLinkText_status_201

- src/test/java/school/redrover/GroupIntroVertsQaTest.java
Changed class GroupIntroVertsQaTest:
1. extends BaseTest
2. add "Ignore" annotation to each test 
3. refactored AkiMira test to BaseTest
> AkiMiraRefactoring

- src/test/java/school/redrover/LocomotiveGroupTest.java
-Добавил тест по проверке поисковой строки яндекса
> -DF:yandexSearchBarTest

- src/test/java/school/redrover/ArSaFirstTest.java
3 Tests
1.Check if Title of the Website is correct.
2.Check if the form "Text Input" is working, try to input some text, check the input text
3.Check "my-disabled" element for the following functions: is disabled, is visible and the placeholder text is correct.
4.Check the color of "my-colors" element
> ArSaFirstTest

- src/test/java/school/redrover/GroupIntroVertsQaTest.java
- src/test/java/school/redrover/LocomotiveGroupTest.java
Class LocomotiveGroupTest was extends BaseTest.
TextBox and Link tests were refactored. 
Other tests were ignored.
> TextBox and Link tests refactoring

- src/test/java/school/redrover/GroupUnderdogsTest.java
> GroupUnderdogs - Tereshenkov - refactoring code - adding inheritance from the BaseTest class

- src/test/java/school/redrover/GroupJavaBustersTest.java
BaseTest class has been extended, refactoring of Nikolay's tests, added ignore annotation for all other tests
> BaseTest class has been extended

- src/test/java/school/redrover/LocomotiveGroupTest.java
> test with command Locomotive

- src/test/java/school/redrover/GroupJavaBustersTest.java
a popup check has been added to the first two test methods
> refactoring

- src/test/java/school/redrover/LocomotiveGroupTest.java
> Df refactor test

- src/test/java/school/redrover/PlusThreeTest.java
> Made changes my test according to lesson 19

- src/test/java/school/redrover/GroupIntroVertsQaTest.java
1. Ignore my unstable test (DEMOQA)
2. Add new test (https://www.saucedemo.com)
> Aki Mira refactoring and add new test

- src/test/java/school/redrover/GroupJavaPlaywrightTest.java
Add testCreateFreeStyleProject()
> Add testCreateFreeStyleProject()

- src/test/java/school/redrover/GroupSurvivorsTest.java
The refactoring of testEvgenyFindJavaPage was made in accordance with the requirements of Lecture No. 19
> testEvgenyFindJavaPage refactoring

- src/test/java/school/redrover/GroupJavaJitsuTest.java
> firstTest Refactoring

- src/test/java/school/redrover/GroupUnitedByJavaTest.java
> Add new test

- src/test/java/school/redrover/GroupUnicornsTest.java
jenkins test 
testJenkinsAddDescr
> jenkins test

- src/test/java/school/redrover/GroupJavaBustersTest.java
> Fill inform test/marta

- src/test/java/school/redrover/GroupJavaBustersTest.java
> refactoring fillInFormTest

- src/test/java/school/redrover/GroupUnicornsTest.java
> Adds a new test

- src/test/java/school/redrover/GroupUnderdogsTest.java
- adding comment for "WebDriver driver;" line
- changing name for MAIN_PAGE_URL_99BOTTLES constant
- refactoring of 3 my tests (changing URL to constant, changing "driver" to "getDriver()", renaming, removing @Ignore)
> GroupUnderdogs - YT - refactoring of 3 tests

- src/test/java/school/redrover/GroupUnderdogsTest.java
Removed redundant lines
Renamed my tests with 'test' prefix and Username
> GroupUnderdogs_Olgla_Formatting_text

- src/test/java/school/redrover/GroupSevenTest.java
> Changed method name testHPSearch

- src/test/java/school/redrover/BrainBuildersTest.java
- src/test/java/school/redrover/FokichevTest.java
- src/test/java/school/redrover/GroupBrainBuildersTest.java
- src/test/java/school/redrover/GroupHighwayToAqaTest.java
- src/test/java/school/redrover/GroupIntroVertsQaTest.java
- src/test/java/school/redrover/GroupJavaAutomationTest.java
- src/test/java/school/redrover/GroupJavaExplorersTest.java
- src/test/java/school/redrover/GroupJavaPlaywrightTest.java
- src/test/java/school/redrover/GroupSevenTest.java
- src/test/java/school/redrover/GroupUnderdogsTest.java
- src/test/java/school/redrover/GroupUnicornsTest.java
- src/test/java/school/redrover/GroupUnitedByJavaTest.java
- src/test/java/school/redrover/NikolaevaTest.java
- src/test/java/school/redrover/PlusThreeTest.java
- src/test/java/school/redrover/XLosTest.java
added assert that new project was created
> New Test Jenkins

- src/test/java/school/redrover/AlexChTest.java
Added tests - checkJenkinsVersionTest, createPipelineWithCorrectNameTest, createPipelineWithEmptyNameTest and createPipelineWithDuplicateNameTest
> add new tests

- src/test/java/school/redrover/GroupSevenTest.java
> Jenkins About test

- src/test/java/school/redrover/GroupUnderdogsTest.java
> New Jenkins test

- src/test/java/school/redrover/GroupUnitedByJavaTest.java
Добавила первый тест по Jenkins
> Homework First JenkinsTest

- src/test/java/school/redrover/LocomotiveGroupTest.java
Added Jenkins test which verifies the current version of Jenkins
> add test verify Jenkins version

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
Маленький тест, для проверки Push.
> Trial test.

- src/test/java/school/redrover/PavTomakTest.java
- src/test/java/school/redrover/runner/BaseTest.java
update code to use driver from BaseTest, add two initial Jenkins tests
> Pav Tomak solitary test

- src/test/java/school/redrover/GroupIntroVertsQaTest.java
Ignore problem test by Dmitriy (DemoQA)
Add new Test Jenkins Search Field
Refactoring my tests
> Aki mira jenkins search field test

- src/test/java/school/redrover/GroupUnicornsTest.java
Test my study page with corrected test
> added Jenkins tests (#620)

- src/test/java/school/redrover/KuzminaTest.java
refactoring and added one more step in the test. Test passed.
> Sk refactoring nationalpark test

- src/test/java/school/redrover/PetrovTest.java
add testCreateJenkinsProject
remove my old tests
> add jenkins test

- src/test/java/school/redrover/GroupUnicornsTest.java
Please, check and approve my PR
> adding first Jenkins test and deleting my old test

- src/test/java/school/redrover/GroupJavaJitsuTest.java
> created and renamed freestyle project

- src/test/java/school/redrover/FirstTest.java
- src/test/java/school/redrover/KPNewItemTest.java
Testing the "New Job" page.
Notification about the absence of entered text.
Inability to click the "OK" button without entering text.
> Kp Testing the "New Job" page.

- src/test/java/school/redrover/GroupJavaBustersTest.java
> Sign in Jenkins

- src/test/java/school/redrover/GroupJavaJitsuTest.java
refactored FreestyleProject and RenameFreestyleProject tests. 
Created a separate method that creates freestyle projects.
> refactored FreestyleProject and RenameFreestyleProject tests. 

- src/test/java/school/redrover/VasilyiDrakeTest.java
> Make some Jenkins Tests

- src/test/java/school/redrover/GroupCarlTheFogTest.java
Created method which creates Freestyle Project.
Refactored testCreateNewFreestyleProject.
Added new testRenameFreestyleProject.
> Deleted non Jenkins tests.

- src/test/java/school/redrover/ArSaFirstTest.java
1.Delete old tests
2.Add a Test for Jenkins
3. Add asserts
> ArSa/Test for Jenkins

- src/test/java/school/redrover/PopovTest.java
> AP new Jenkins tests

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
> testComparisonManageSystem - изменил локаторы.

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
testAddingDescriptionUser - Добавил новый тест. Тренируюсь.
> testAddingDescriptionUser - Добавил новый тест.

- src/test/java/school/redrover/GroupIntroVertsQaTest.java
- add new item freetstyle project positive test
- refactoring test of Jenkins search field
> AkiMira New Item Freestyle Project Positive Test

- src/test/java/school/redrover/GroupSevenTest.java
Add @Ignore to not Jenkins tests
> Adds new test

- src/test/java/school/redrover/GroupUnicornsTest.java
Created test for Admin and Description
> Test Admin and Description

- src/test/java/school/redrover/LocomotiveGroupTest.java
This test ads a new job and verifies that it is added to the job list Jenkins.
> Add new Jenkins test for class LocomotiveGroupTest.java, 

- src/test/java/school/redrover/GroupCarlTheFogTest.java
Switched method createNewFreestyleProject from public to private.
> Added test which is deleted FreestyleProject from side menu.

- src/test/java/school/redrover/GroupJavaPlaywrightTest.java
Reemove Ignore, fix testAddDescriptionFromMyViewsPage()
> Reemove Ignore, fix testAddDescriptionFromMyViewsPage()

- src/test/java/school/redrover/GroupCarlTheFogTest.java
Add create Pipeline and add description Tests
> Create Pipeline and add description Tests

- src/test/java/school/redrover/LocomotiveGroupTest.java
> add testCreateOrganizationFolder

- src/test/java/school/redrover/GroupUnicornsTest.java
added Create Project
added Delete Project
> My First Jenkins Test

- src/test/java/school/redrover/FreestyleProject2Test.java
https://trello.com/c/XCo8s5sQ/52-tc0000102-creating-new-item-creating-freestyle-project
> TC_00.001.02 | Add create FreeStyle project

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/dwQUwvrj/53-tc0400101-folder-rename-folder
Test for rename folder from drop-down menu
> TC_04.001.01 | Folder > Rename Folder 

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/F1bGk3d0/9-tc0000101-new-freestyle-project-is-created-using-valid-name
> TC_00.001.01 New Freestyle project is created using valid name

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/JUTGgppj/69-tc0100301-freestyleproject-delete-project
> TC_01.003.01 | FreestyleProject > Delete project

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/fOejrosf/56-tc0000201-create-pipeline-with-valid-name
> TC_00.002.01 | Create Pipeline with valid name

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/dR4e3iQx/73-tc0100201-freestyleproject-rename-project
> TC_01.002.01 FreestyleProject > Rename project

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/NMK1Ux2b/64-tc0400101-folder-rename-folder
> TC_04.001.01_Rename_Folder

- src/test/java/school/redrover/FooterTest.java
https://trello.com/c/Qj8qt6Zv/81-tc1200102-footer-jenkins-version-viewing-the-jenkins-version
> TC_12.001.02 add version test

- src/test/java/school/redrover/FooterTest.java
https://trello.com/c/YANIrhP7/84-tc1200201-footer-rest-api-link-visibility-and-clickability-verify-clickability-of-rest-api-link
> TC_12.002.01 added new test for verifying clickability of REST API link

- src/test/java/school/redrover/FooterTest.java
https://trello.com/c/SoXkjxWl/85-tc1200401-footer-rest-api-link-redirection
> TC_12.004.01 add test redirected rest api

- src/test/java/school/redrover/HeaderTest.java
Added HeaderTest class with 1 return with logo test
https://trello.com/c/K2wyB2Jw/90-tc1400101-header-return-to-the-dashboard-page-with-one-click
> TC_14.001.01

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/90DW5VUQ/54-us0200701-pipeline-rename-project
> TC_02.007.01 | Pipeline > Rename project

- src/test/java/school/redrover/Pipeline2Test.java
[TC] - https://trello.com/c/CGD6510k
> TC_00.002.04 | Creating new item > Creating Pipeline > Verify creation of a pipeline from the main panel

- src/test/java/school/redrover/RestApiLlinkTest.java
> TC_12.002.01 | Footer > REST API link > Visibility and clickability

- src/test/java/school/redrover/NodesTest.java
https://trello.com/c/WJI5845H/93-tc1500201-rename-existing-node-with-valid-name-from-nodes-page
> TC_15.002.01 | Add test rename node

- src/test/java/school/redrover/PipelineTest.java
> TC_02.007.02 | Pipeline > Add Rename Pipeline Test

- src/test/java/school/redrover/Pipeline2Test.java
Creates method for pipeline creation, adds delete pipeline test
> TC_02.005.01 | Pipeline> Delete project > Verify delete project through the side panel

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/jbLftoiS/102-tc0100102-freestyleproject-add-desription
> Added new testAddDescriptionFreestyleProject - TC_01.001.02

- src/test/java/school/redrover/OrganizationFolder2Test.java
https://trello.com/c/n7upqVAh/91-tc0600301-organization-folder-rename-organization-folder
> TC_06.003.01 | Add Rename Organization Folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/0x7KcPGb/108-tc0000001-creating-new-item-creating-freestyle-project
> TC_00.001.01 Creating new item > Creating Freestyle project

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/vXDvnBr5/79-tc0000402-folder-move-folder-to-folder
> TC_00.004.02 | Add test move Folder to Folder

- src/test/java/school/redrover/NodesTest.java
https://trello.com/c/lw3GpFaF/111-tc1500103-nodes-create-new-node-by-clicking-on-build-executor-status-in-side-panel-menu
> TC_15.001.03 create New Node By Build Executor In Side Panel Menu

- src/test/java/school/redrover/Pipeline3Test.java
[TC_00.002.06 | Creating new item > Creating Pipeline](https://trello.com/c/bATmCjh2/88-tc0000206-creating-new-item-creating-pipeline)
> TC_00.002.06 | Creating Pipeline

- src/test/java/school/redrover/ViewTest.java
https://trello.com/c/Ttrkh9rl/94-tc1000101-views-create-new-view
> TC_10.001.01 | add test Create new view

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/ClYuoFYv/118-tc0400106-folder-rename-folder-invalid-name
> TC_04.001.06 | Folder > Rename Folder > Invalid Name

- src/test/java/school/redrover/FreestyleProject2Test.java
https://trello.com/c/2PvwZokE/122-tc0000101-creating-new-item-creating-frestyle-project
> TC_00.001.01 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/OrganizationFolderTest.java
> TC_06.004.01 | Organization folder > Disable Organization folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/DCkr1aXP/119-tc01006001-freestyle-project-configure-general-settings-the-tooltip-message-is-displayed-near-the-checkbox-discard-old-builds
> TC_01.006.001 testTooltipDiscardOldBuildsIsVisible added

- src/test/java/school/redrover/Folder2Test.java
https://trello.com/c/T8f47Qbt/124-tc0000503-new-item-organization-folder-create-organization-folder
> TC_00.005.03 | Add create new Organization Folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/EiT5gEdA/129-tc0100103-freestyleproject-add-description
> TC_01.001.03 | FreestyleProject > Add description

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/Zb1XW7Un/59-tc0000203-create-pipeline-with-dublicate-name
> TC_00.002.03 Create Pipeline with dublicate name

- src/test/java/school/redrover/Folder2Test.java
- src/test/java/school/redrover/Folder4Test.java
[https://trello.com/c/b5lK9hgw/110-tc0400202-folder-move-folder-to-folder](https://trello.com/c/b5lK9hgw/110-tc0400202-folder-move-folder-to-folder)
> TC_04.002.02 | Folder > Move Folder to Folder

- src/test/java/school/redrover/OrganizationFolder3Test.java
https://trello.com/c/oZW46Cpt/136-tc00005-new-item-organization-folder-create-organization-folder
> TC_00.005 | Create Organization Folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/8CkRVxzP/130-tc0100104-freestyleproject-edit-the-existing-description
> TC_01.001.04 | FreestyleProject > Edit the existing description

- src/test/java/school/redrover/OrganizationFolderRenameTest.java
https://trello.com/c/HMdF1Lmx/139-tc000000-us06003-organization-folder-rename-organization-folder
> TC_06.003.02 | Organization folder > Rename Organization folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/9dDTYYRW/131-tc0100105-freestyleproject-delete-the-existing-description
> TC_01.001.05 | FreestyleProject > Delete the existing description

- src/test/java/school/redrover/Pipeline2Test.java
> TC_02.001.01 | Pipeline > View pipeline page > Verify the pipeline description displays

- src/test/java/school/redrover/CheckJenkinsVersionTest.java
https://trello.com/c/KfrN22iD/142-tc1200103-footer-jenkins-version-viewing-the-jenkins-version
> Els/tc 12.001.03/jenkins version

- src/test/java/school/redrover/OrganizationFolder3Test.java
https://trello.com/c/L8Sbvk49/149-tc00005-new-item-organization-folder-create-organization-folder-with-invalid-name
> TC_00.005 | Create Organization Folder with invalid data

- src/test/java/school/redrover/FolderBayanTest.java
here is the Test case 
https://trello.com/c/AZlAR8HB/109-tc0400104-folder-rename-folder-through-side-panel
> TC_04.001.04 | Rename Folder through side panel AND TC_04.001.05 | Folder > Rename Folder - Check error when no name is specified

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/wAEFKBBw/123-rf000001-code-review-tc0400102-us04001
> RF_000.001 refactoring TC_04.001.02 > US_04.001

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/XhhcfSQP/148-tc0000106-creating-new-item-creating-freestyle-project-using-valid-name
> TC_00.001.06 | add test Creating new Freestyle project using valid name

- src/test/java/school/redrover/BreadcrumbTest.java
> TC_11.002.01 | Breadcrumb > Return on Main Page From Any Page by click Dashboard

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/6nUJhdtp/66-tc0000106-creating-new-item-creating-freestyle-project
> TC_00.001.06 | add create Freestyle Project

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/ijmX11ag/133-tc0000104-creating-new-item-creating-freestyle-project-using-invalid-name
> TC_00.001.04 | add test Creating Freestyle project using invalid name

- src/test/java/school/redrover/ViewTest.java
https://trello.com/c/5OnVYBs7/156-tc1000201-views-edit-view-rename-view
> TC_10.002.01 | Add test Rename View

- src/test/java/school/redrover/OrganizationFolder3Test.java
https://trello.com/c/HsRg6y1u/162-tc00005-new-item-organization-folder-create-organization-folder-with-space
> TC_00.005 | Create Organization Folder with Space

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/ClUjLWyu/157-tc0100401-freestyle-project-disable-project
> TC_01.004.01 | Freestyle project > Disable project

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/EChMOobi/151-us01001-freestyleproject-add-desription
> US_01.001.01 | Add testAddDescription

- src/test/java/school/redrover/FreestyleProject4Test.java
https://trello.com/c/DnJlBt4A/165-tc0000108-creating-new-item-creating-freestyle-project
> TC_00.001.08 | create FreestyleProject4

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/9csCKUoq/89-tc0000701-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.01 Add create Folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/pXuMOCve/144-tc0000105-creating-new-item-creating-freestyle-project-using-an-empty-name
> TC_00.001.05 | Add test Creating Freestyle project using an empty name

- src/test/java/school/redrover/OrganizationFolder3Test.java
https://trello.com/c/XpEwpWzq/161-tc00005-new-item-organization-folder-create-organization-folder-with-empty-name
> TC_00.005 | Create Organization Folder with Empty Name

- src/test/java/school/redrover/Pipeline2Test.java
> TC_02.001.02 | Pipeline > View pipeline page > Verify permalinks section before builds

- src/test/java/school/redrover/Pipeline2Test.java
> TC_02.001.03 | Pipeline > View pipeline page > Verify permalinks section after a build

- src/test/java/school/redrover/MultibranchPipeline2Test.java
https://trello.com/c/Ep63DZqa/128-tc0000602-check-the-display-of-multibranch-pipeline-name
> TC_00.006.02 | Check the display of Multibranch Pipeline name

- src/test/java/school/redrover/ViewTest.java
https://trello.com/c/Mqiw9dXb/95-tc1000102-views-create-new-view
> Td/tc 10.001.02 - create new view

- src/test/java/school/redrover/RestApiLink2Test.java
https://trello.com/c/OT97hjGK/187-tc1200402-footer-rest-api-link-redirection
> Am/tc 12.004.02 | restApiRedirection

- src/test/java/school/redrover/MulticonfigurationProjectTest.java
https://trello.com/c/EQ6Vo8dN/61-tc0000301-creating-new-item-creating-multiconfiguration-project-create-multiconfiguration-project-with-valid-name
> TC_00.003.01 Create Multiconfiguration project with valid name

- src/test/java/school/redrover/FolderBayanTest.java
https://trello.com/c/qKuYXV9W/180-tc0400107-folder-rename-folder-check-error-unsafe-character
https://trello.com/c/2lI25hTY/184-tc0400108-folder-rename-folder-check-error-for-an-ending-period
> TC_04.001.07 | Folder > Rename Folder - Check errors

- src/test/java/school/redrover/FreestyleProjectTest.java
TC_01.004.02 | Disable project on Configure page
> TC_01.004.02 | Freestyle project > Disable project on Configure page

- src/test/java/school/redrover/FreestyleProject4Test.java
https://trello.com/c/SMHVp9jZ/206-tc01001-freestyleproject-add-desription
> TC_01.001.06 | FreestyleProject > Add desription

- src/test/java/school/redrover/FreestyleProject5Test.java
https://trello.com/c/zdtzVDtq/222-tc0100304-freestyle-project-delete-project
> TC_01.003.04 |Freestyle project > Delete project

- src/test/java/school/redrover/View2Test.java
https://trello.com/c/9Y3oPtje/141-tc1000103-views-create-new-view
> TC_10.001.03 | Views >Create new view

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/OtnOcKUC/209-tc0000111-creating-new-item-creating-freestyle-project-with-valid-name
> TC_00.001.11 | Creating new item > Creating Freestyle project with valid name

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/2ORsxbU3/219-tc0000704-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.04 |Creat New Folder

- src/test/java/school/redrover/OrganizationFolderTest.java
> TC_06.005.01 | Organization folder > Delete Organization folder

- src/test/java/school/redrover/Pipeline2Test.java
ТС - https://trello.com/c/kAZwAAJB
> TC_02.001.04 | Pipeline > View pipeline page > Verify stage view section before a build

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/gxpLsrAz/194-tc0000110-creating-new-item-creating-freestyle-project
> TC_00.001.10 | Create Freestyle project

- src/test/java/school/redrover/FreestyleProject6Test.java
https://trello.com/c/rAN5Jvmn/220-tc0000108-creating-new-item-creating-freestyle-project
> TC_00.001.08 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/Pipeline5Test.java
https://trello.com/c/mXhlz1I1/225-tc0000211-creating-new-item-creating-pipeline
> TC_00.002.11 | Creating new item > Creating Pipeline

- src/test/java/school/redrover/OrganizationFolder6Test.java
https://trello.com/c/c5EOLNUR/229-tc0000000-item-sub-item-tc-title
> TC_00.005.07 | New Item > Organization Folder > Create Organization Folder

- src/test/java/school/redrover/FreestyleProject6Test.java
https://trello.com/c/6f8o2EPK/87-tc0100302-freestyleproject-delete-project
> TC_01.003.02 | FreestyleProject > Delete project

- src/test/java/school/redrover/Pipeline5Test.java
- src/test/java/school/redrover/PipelineDeleteTest.java
> TC_00.002.05 | Pipeline> Delete project

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/w3Hcz2Ux/234-tc0100204-freestyle-project-rename-project-rename-project-to-empty-name
> TC_01.002.04 | Freestyle project > Rename project > Rename project to  empty name

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/HeaderTest.java
Added 2 tests to enable and disable new Freestyle project
https://trello.com/c/6tzKOy5x/166-tc0100401-freestyle-project-enable-or-disable-project
> TC_01.004.01

- src/test/java/school/redrover/HeaderTest.java
added new test for verifying return for Main page from Main menu items pages by clicking Jenkins Logo
https://trello.com/c/WWqcPHcX/120-tc1400102-header-return-to-the-dashboard-page-with-one-click-verify-return-to-main-page-from-main-menu-items-pages-by-clicking-j
> TC_14.001.02 Header > Return to the dashboard page with one click > Verify Return to Main page from Main Menu Items pages by clicking Jenkins Logo

- src/test/java/school/redrover/BreadcrumbTest.java
>  added test change 

- src/test/java/school/redrover/Folder6Test.java
https://trello.com/c/cVMMpTdT/249-tc0000705-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.05 | Add test for creating folder

- src/test/java/school/redrover/Pipeline6Test.java
> test: TC_02.001.05 create Pipeline

- src/test/java/school/redrover/FreestyleProjectTest.java
TC - https://trello.com/c/BGX932BO
> TC_01.002.05 | Freestyle project > Error if rename project with existing name

- src/test/java/school/redrover/NodesTest.java
https://trello.com/c/G4IPG4iV/259-tc1500106-nodes-create-new-node
> test Create NewNode From Nodes Section In Manage Jenkins Page

- src/test/java/school/redrover/NodesTest.java
https://trello.com/c/zgkWL2UC/262-rf0000000-item-sub-item-us-title
> RF_15.001.03 added variable NODE_NAME, used goToNodesPage()

- src/test/java/school/redrover/Folder6Test.java
https://trello.com/c/Nov6wncY/250-tc0000510-new-item-organization-folder-create-organization-folder
> TC_00.005.10 | add create Folder

- src/test/java/school/redrover/CreatingPipelineTest.java
> TC_00.002.07 Creating Pipeline add test

- src/test/java/school/redrover/FreestyleOmegakotTest.java
> TC_01.001.05 FreestyleProject - Add description test

- src/test/java/school/redrover/PipelineTest.java
+ update createPipeline method
+ remove commented code
> TC_02.003.03 | Pipeline > Build now > Verify build status icon is displayed on Dashboard after build

- src/test/java/school/redrover/FreestyleProject12Test.java
- src/test/java/school/redrover/FreestyleProject4Test.java
https://trello.com/c/3Kp9gtFQ/153-tc0000104-creating-new-item-creating-freestyle-project
> TC_00.001.04 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/FreestyleProjectVDTest.java
> TC_01.006.07 | Freestyle project > Configure General settings > Add a link to GitHub in GitHub project section

- src/test/java/school/redrover/Folder7Test.java
https://trello.com/c/pH1eSZaP/277-us0400204-folder-move-folder-to-folder
> TC_04.002.04 Add Move Folder to Folder

- src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/HqLTEwyT/246-tc0000509-new-item-organization-folder-create-organization-folder-with-valid-name
https://trello.com/c/Fi4lUshV/233-tc0000508-new-item-organization-folder-create-organization-folder-displaying-an-error-when-the-item-name-field-is-empty
> Kristina - my tests Jenkins

- src/test/java/school/redrover/FreestyleProject2Test.java
https://trello.com/c/0C39zCnR/75-tc0100202-freestyle-project-rename-project
> add test  TC_01.002.05  Freestyle Project. Rename project

- src/test/java/school/redrover/View3Test.java
https://trello.com/c/LFTg31Fz/302-tc1000203-views-edit-view-verify-the-view-could-be-renamed
> TC_10.002.03 | Views > Edit view > Verify the View could be renamed

- src/test/java/school/redrover/View3Test.java
https://trello.com/c/k2lUmuhJ/305-tc1000204-views-edit-view-verify-the-description-could-be-added-to-the-view
> TC_10.002.04 | Views > Edit view > Verify the description could be added to the View

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/GbOueOxT/173-us0100201-freestyleproject-rename-project
> TC_01.002.01 | add Rename Project Test

- src/test/java/school/redrover/View3Test.java
https://trello.com/c/Tbe8rnrQ/306-tc1000205-views-edit-view-verify-the-description-of-the-view-could-be-edited
> TC_10.002.05 | Views > Edit view > Verify the description of the View could be edited

- src/test/java/school/redrover/FreestyleProjectIldanaTest.java
https://trello.com/c/YAPXjd7b/80-tc0100101-freestyleproject-add-desription
> US_01.001 FreestyleProject  Add desription

- src/test/java/school/redrover/FreestyleProject7Test.java
https://trello.com/c/0QOWHMy1/315-us0000105-item-sub-item-tc-title
> TC_00.001.05 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/FolderBayanTest.java
https://trello.com/c/tm5ILS4l/190-tc04002034-folder-move-folder-to-folder-through-context-menu
> TC_04.002.034| Folder > Move Folder to Folder through context menu

- src/test/java/school/redrover/Pipeline2Test.java
> TC_02.001.06 | Pipeline > View pipeline page > Verify stage view section after configure with a build sample 

- src/test/java/school/redrover/OrganizationFolder7Test.java
> TC_00.005.15 | New Item > Organization Folder > Create Organization Folder

- src/test/java/school/redrover/FreestyleProjectVDTest.java
> TC_01.006.10 | Freestyle project > Configure General settings > Select Discard old builds checkbox 

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/E2OQGd0p/243-tc0000100-creating-new-item-creating-freestyle-project
> TC_00.001.11 Creating new item > Creating Freestyle project > Freestyle project with empty name

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/HAbOnuwY/317-tc01006002-freestyle-project-configure-general-settings-the-help-description-of-discard-old-builds-is-visible
> TC_01.006.002 | The help description of Discard old builds is visible

- src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/lo3JbKtJ/297-tc0600402-disable-organization-folder
> TC_06.004.02 disable existing Organization folder

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/MlVEm0qJ/321-tc0200706-pipeline-verify-the-error-message-no-name-is-specified-in-case-of-attempt-to-save-the-empty-name
> TC_02.007.06 | Add Pipeline Rename No name check

- src/test/java/school/redrover/FreestyleProject1Test.java
- src/test/java/school/redrover/FreestyleProject7Test.java
https://trello.com/c/xIEfZGMy/285-tc0000112-creating-new-item-creating-freestyle-project
> TC_00.001.12 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/OrganizationFolderTest.java
> TC_06.005.01|Verify that Organization folder deleted

- src/test/java/school/redrover/Node2Test.java
https://trello.com/c/KGJ3Arc0/318-tc1500107-nodes-create-node-from-jenkins-main-panel
> N stepanova/tc 15.001.07

- src/test/java/school/redrover/Folder8Test.java
https://trello.com/c/7ePmTiHS/324-tc0000707-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.07 | Add Create a new Folder

- src/test/java/school/redrover/FreestyleProjectVDTest.java
> TC_01.006.12 | Freestyle project > Configure General settings > Select Throttle builds checkbox

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/ltLcna13/303-tc0000208-creating-new-item-creating-pipeline
> TC_00.002.08 | Add create Pipeline

- src/test/java/school/redrover/FreestyleProject10Test.java
- src/test/java/school/redrover/FreestyleProject7Test.java
https://trello.com/c/VHTJP5Tk/253-tc0000112-creating-new-item-creating-freestyle-project
> TC_00.001.12 | Creating Freestyle project

- src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/C49z6aDU/323-tc0600403-organization-folder-disable-organization-folder-by-button-disable-organization-folder
> TC_06.004.03 | Organization folder Disable By Button

- src/test/java/school/redrover/View3Test.java
https://trello.com/c/89lCiYyy/307-tc1000206-views-edit-view-verify-the-description-of-the-view-could-be-fully-deleted
> TC_10.002.06 | Views > Edit view > Verify the description of the View could be fully deleted

- src/test/java/school/redrover/MulticonfigurationProjectTest.java
https://trello.com/c/ArWqecXG/62-tc0000302-creating-new-item-creating-multiconfiguration-project-create-multiconfiguration-project-with-empty-name
> TC_00.003.02 Create Multiconfiguration project with empty name

- src/test/java/school/redrover/FreestyleProject10Test.java
- src/test/java/school/redrover/Pipeline7Test.java
https://trello.com/c/hr4FHqZX/332-tc0000207-creating-new-item-creating-pipeline
> TC_00.002.07 | Creating new item > Creating Pipeline

- src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/C49z6aDU/323-tc0600403-organization-folder-disable-organization-folder-by-button-disable-organization-folder
Adding a second check with message "This Organization Folder is currently disabled"
> TC_06.004.03 | Organization folder Adding a second check

- src/test/java/school/redrover/FreestyleProject1Test.java
https://trello.com/c/gGL5VxF2/295-tc01003012-freestyle-project-delete-project
> TС_01.003.012

- src/test/java/school/redrover/Folder9Test.java
https://trello.com/c/dUrIP4eh/343-tc0000708-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.08 | Creating new item > Folder item > Creating a new Folder

- src/test/java/school/redrover/FreestyleProject1Test.java
> TC_01.010.01 | Freestyle project > Configure Build Environment settings > Add timestamps to the Console Output

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/Ssh21UFp/335-tc050021-multibranch-pipeline-rename-multibranch-pipeline-from-sidebar-on-the-existing-multibranch-pipeline-pagee
> TC_05.002.1 Multibranch pipeline Rename Multibranch pipeline from sidebar on the existing Multibranch pipeline page

- src/test/java/school/redrover/FreestyleProject2Test.java
https://trello.com/c/snFjcypK/299-tc0100314-freestyle-project-delete-project
> add test TC_01.003.14 delete Freestyle project

- src/test/java/school/redrover/Folder3Test.java
https://trello.com/c/ez3CjPnk/263-tc0400109-rename-folder-from-drop-down-menu-next-to-folder-name
> TC_04.001.09 | Rename folder from drop-down menu next to folder name

- src/test/java/school/redrover/FreestyleProject7Test.java
[TC]- https://trello.com/c/37Kcagnk/361-tc0101401-freestyle-project-item-view-permalinks-for-builds-verify-the-permalinks-are-displayed-after-clicking-build-now
> TC_01.014.01 | Freestyle project Item > > View Permalinks for builds > Verify the permalinks are displayed after clicking Build Now

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/UN7confO/345-tc0100211-freestyle-project-rename-the-project-with-other-valid-name-from-the-left-side-menu-on-the-project-page
> TC_01.002.11 | Freestyle project > Rename the project with other valid name from the left side menu on the project page

- src/test/java/school/redrover/FreestyleProject13Test.java
https://trello.com/c/5pSbJyxk/370-tc0000113-creating-new-item-creating-freestyle-project
> TC_00.001.13 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/MultibranchPipeline3Test.java
- src/test/java/school/redrover/MultibranchPipelineTest3.java
https://trello.com/c/UY7DR1Qm/152-tc0000603-new-item-create-multibranch-pipeline
> TC_00.006.03 | New Item > Create Multibranch Pipeline

- src/test/java/school/redrover/FreestyleProject4Test.java
https://trello.com/c/B44kk8EW/365-tc0100108-freestyle-project-edit-the-existing-description
> TC_01.001.08  | Freestyle project > Edit the existing description

- src/test/java/school/redrover/ViewTest.java
https://trello.com/c/QMcbKRcy/231-tc1000106-views-create-new-view
> TC_10.001.06 | Views > Create new view

- src/test/java/school/redrover/FooterTest.java
https://trello.com/c/VwzZ3fZs/254-tc1200105-footer-jenkins-version-viewing-the-jenkins-version
> TC_12.001.05 | Footer > Jenkins version > Viewing the Jenkins version

- src/test/java/school/redrover/Folder10Test.java
- src/test/java/school/redrover/runner/Folder10Test.java
https://trello.com/c/ISd5oAxu/374-tc0000709-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.09| Creating new item > Folder item > Creating a new Folder

- src/test/java/school/redrover/Folder10Test.java
https://trello.com/c/aUMJSrmk/248-tc0000706-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.06 Create folder

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/WZTGz4XV/369-tc01006003-freestyle-project-configure-general-settings-the-help-description-of-discard-old-builds-is-closed-after-clickinh-agai
> TC_01.006.004| The 'Discard old builds' settings are displayed

- src/test/java/school/redrover/Node2Test.java
https://trello.com/c/xl1qAkMH/334-tc1500109-node-create-node-from-build-executor-status
> N stepanova/tc 15.001.09

- src/test/java/school/redrover/FreeStyleProject8Test.java
- src/test/java/school/redrover/FreeStyleProjectCreationTest.java
https://trello.com/c/03u6Umlz/367-tc0000101-creating-new-item-creating-freestyle-project
> TC_00.001.01 |Creating new item > Creating Freestyle project

- src/test/java/school/redrover/ViewTest.java
Refactor and Fix. Remove `@Ignore`.
https://trello.com/c/5OnVYBs7/156-tc1000201-views-edit-view-rename-view
> TC_10.002.01 | Refactor

- src/test/java/school/redrover/OrganizationFolder3Test.java
https://trello.com/c/qvedLvZk/241-tc0600300-organization-folder-rename-organization-folder-from-dashboard-dropdown-menu
> TC 06.003 | Rename Organization folder from Dashboard dropdown menu

- src/test/java/school/redrover/FreestyleMoveToFolderTest.java
https://trello.com/c/g3NneYxV/368-tc0101502-freestyle-project-move-project
> TC_01.015.02 | Freestyle project > Move Project

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/CLylSYT7/373-tc0100602-freestyle-project-configure-general-settings-this-project-is-parameterized-checkbox
> TC_01.006.02 | Freestyle project > Configure General settings > This project is parameterized checkbox selected

- src/test/java/school/redrover/OrganizationFolder3Test.java
https://trello.com/c/pjliT0vm/242-tc0600300-organization-folder-rename-project-with-the-same-name
> TC 06.003 | Rename Organization folder with the same name

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/e4n6HJAr/101-tc0000205-creating-new-item-creating-pipeline-create-a-pipeline-with-a-valid-name
> TC_00.002.05_CreatePipeLineValidName

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/ygw8jCYj/376-tc0100401-freestyle-project-enable-or-disable-project-disable-the-freestyle-project-when-creating-the-project
https://trello.com/c/G1HXNqud/211-tc0100409-freestyleproject-enable-or-disable-project-disable-the-freestyle-project-from-configure-project-page
> TC_01.004.01 | Freestyle project > Enable or disable project > Disable the freestyle project when creating the project

- src/test/java/school/redrover/ViewTest.java
https://trello.com/c/0Q3bBfZW/347-tc1000301-views-delete-view
> TC_10.003.01 | delete_new_view

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/21HMpca1/381-rf0100611-freestyle-project-configure-general-settings-select-this-project-is-parameterized-checkbox
> RF_01.006.11 | Freestyle project > Configure General settings > Select This project is parameterized checkbox

- src/test/java/school/redrover/MulticonfigurationProject2Test.java
https://trello.com/c/A50QoxAz/398-tc00003-creating-new-item-creating-multiconfiguration-project
> TC_00.003.04 Creating new item > Creating Multiconfiguration project

- src/test/java/school/redrover/FooterTest.java
https://trello.com/c/3ie7dy8O/403-tc1200108-footer-jenkins-version-about-jenkins
> TC_12.001.08 | Footer > Jenkins version > About Jenkins

- src/test/java/school/redrover/Pipeline5Test.java
> TC_02.007.04 | Pipeline > Rename project > Verify rename from the left menu

- src/test/java/school/redrover/FreestyleProjectPopovTest.java
https://trello.com/c/EH7Qrl7n/121-tc0000103-creating-new-item-creating-freestyle-project
> TC_00.001.03 | Add Creating Freestyle project

- src/test/java/school/redrover/FreestyleProject13Test.java
- src/test/java/school/redrover/FreestyleProject14Test.java
https://trello.com/c/aM9bSSLB/359-tc0000113-creating-new-item-creating-freestyle-project
> TC_00.001.13 Creating new item > Creating Freestyle project

- src/test/java/school/redrover/View4Test.java
https://trello.com/c/ukdWa0P5/386-tc000000000-item-sub-item-us-title
> TC_10.001.07 Views > Create new view

- src/test/java/school/redrover/Folder6Test.java
https://trello.com/c/hrFqIgWe/375-tc0400110-folder-rename-folder#comment-653ff57ce7063f3132178c15
> TC_04.001.10 | add test Rename Folder

- src/test/java/school/redrover/FreestyleProject1Test.java
> TC_01.015.01 | Freestyle project > Move Project > See moved project in the folder

- src/test/java/school/redrover/FolderNewTest.java
> TC_00.007.11 Add create new folder

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/lvdYkszY/415-tc0000000-item-sub-item-tc-title
> TC_01.006.005 | The settings of 'Git' is displayed.

- src/test/java/school/redrover/FreestyleProject1Test.java
https://trello.com/c/BWrAV2tB
**What was changed:**
add the needed assert to check that the list of timestamps is not null Assert.assertNotEquals( timestamps.size(),  0) ;
**Class and method:** 
FreestyleProject1Test  and  testConfigureBuildEnvironmentSettingsAddTimestamp()
> RF_01.010.01 | Freestyle project > Configure Build Environment settings > Add timestamps to the Console Output

- src/test/java/school/redrover/Folder4Test.java
[https://trello.com/c/qFPmmtcJ/393-tc0400501-folder-add-and-edit-description-add-description](https://trello.com/c/qFPmmtcJ/393-tc0400501-folder-add-and-edit-description-add-description)
> TC_04.005.01 | Folder > Add and edit description > Add description

- src/test/java/school/redrover/Folder4Test.java
[https://trello.com/c/vXgNy3Nb/394-tc0400502-folder-add-and-edit-description-edit-description](https://trello.com/c/vXgNy3Nb/394-tc0400502-folder-add-and-edit-description-edit-description)
> TC_04.005.02 | Folder > Add and edit description > Edit description

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/tqB1YfGZ/420-tc0100603-freestyle-project-this-project-is-parameterized-checkbox-ticked
> TC_01.006.03 | Freestyle project > This project is parameterized checkbox ticked

- src/test/java/school/redrover/MyViewsTest.java
TC : https://trello.com/c/8jIxRCJi/326-tc1000106-views-create-new-view-include-a-global-view
testCreateViewWithOptionGlobalView()
> TC_10.001.06 Views Create new view Include a global view

- src/test/java/school/redrover/FreestyleProjectThTest.java
https://trello.com/c/8WCL39sa/422-tc0100203-freestyle-project-rename-project
> TC_01.002.03 | Freestyle project > Rename project

- src/test/java/school/redrover/Folder4Test.java
[https://trello.com/c/wwMNkT3K/385-tc0400301-folder-create-a-new-job-inside-a-folder](https://trello.com/c/wwMNkT3K/385-tc0400301-folder-create-a-new-job-inside-a-folder)
> TC_04.003.01 | Folder > Create a new job inside a folder

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/W6Bs5vf5/414-tc00002-creating-new-item-creating-pipeline
> TC_00.002.13 | Creating new item > Creating Pipeline

- src/test/java/school/redrover/NodeTest.java
https://trello.com/c/HbpV56cE/423-tc1500501-nodes-configure-node-rename-node
> TC_15.005.01 > added testRenameNode

- src/test/java/school/redrover/Pipeline5Test.java
Refactoring and added new test
> TC_02.007.03 Pipeline > Rename Pipeline project from the dropdown menu next to the project name on the home page

- src/test/java/school/redrover/Folder5Test.java
https://trello.com/c/5Vzfposv/419-tc0400305-folder-create-a-new-job-inside-a-folder
> TC_04.003.05 |  Folder > Create a new job inside a folder

- src/test/java/school/redrover/FreestyleProject6Test.java
https://trello.com/c/Qow14fL8/380-tc0100613-freestyle-project-configure-general-settings-select-discard-old-builds-checkbox
> TC_01.006.13 | Freestyle project > Configure General settings > Select Discard old builds checkbox

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/tLpHZCcD/346-tc0100107-freestyle-project-add-desription
> TC_01.001.07  | Freestyle project - Add Description

- src/test/java/school/redrover/View4Test.java
- src/test/java/school/redrover/View6Test.java
test about creating new list view
https://trello.com/c/xBAwfUy8/77-tc1000101-views-create-new-view
> Sk 10.001.01 create view

- src/test/java/school/redrover/FooterTest.java
https://trello.com/c/OOkxIvHX/402-tc1200107-footer-jenkins-version-check-the-tippy-box
> Bayan/tc 12.001.07 footer jenkins version check the tippy box

- src/test/java/school/redrover/FooterTest.java
https://trello.com/c/gS0eOz6x/404-tc1200109-footer-jenkins-version-get-involved
> TC_12.001.09 | Footer > Jenkins version > Get Involved

- src/test/java/school/redrover/MulticonfigurationProject2Test.java
https://trello.com/c/xtHRxXma/383-tc00003001-creating-new-item-creating-multiconfiguration-project
> Marta/tc 00.003.001

- src/test/java/school/redrover/Pipeline7Test.java
https://trello.com/c/0yRYSrdB/236-tc0000203-us02007-pipeline-rename-project
> TC_00.002.03 |US_02.007 | Pipeline > Rename project

- src/test/java/school/redrover/NodeTest.java
https://trello.com/c/jjLVaL1w/427-tc1500502-nodes-configure-node-rename-node-with-incorrect-name
> TC_15.005.02 > added testRenameNodeWithIncorrectName

- src/test/java/school/redrover/View4Test.java
https://trello.com/c/RbWqQvnH/417-tc1000213-views-edit-view-tc-title
> TC_10.002.13 Views > Edit view > View can be renamed

- src/test/java/school/redrover/ViewTest.java
> TC_10.003.03 | Views > Delete view > Deleted view is not displayed on Dashboard

- src/test/java/school/redrover/Pipeline2Test.java
> RF_02.001 | Pipeline > View pipeline page > Verify permalinks section after a build

- src/test/java/school/redrover/FreestyleProjectVDTest.java
> TC_01.006.13 | Freestyle project > Configure General settings > Select Execute concurrent builds if necessary checkbox

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/m6mZbSlE/421-tc0100213-freestyle-project-rename-project
> TC_01.002.13 | Freestyle project > Rename project

- src/test/java/school/redrover/BuildNowTest.java
https://trello.com/c/08JwfERK/188-tc0200301-pipeline-build-now
> TC_02.003.01 | Pipeline > Build now

- src/test/java/school/redrover/Pipeline9Test.java
https://trello.com/c/RtsUKLrm/440-tc00000215-creating-new-item-creating-pipeline
> TC_000.002.15 | add a Pipeline9Test

- src/test/java/school/redrover/Folder2Test.java
https://trello.com/c/RogIKThg/433-tc000001030-creating-new-item-creating-freestyle-project
> TC_000.001.030 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/Folder2Test.java
- src/test/java/school/redrover/FreestyleProject1Test.java
- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/eLKfBChK/450-tc0000000-item-sub-item-us-title
> AK_84_TC_000.002.020

- src/test/java/school/redrover/Pipeline2Test.java
> TC_02.004.04 | Pipeline > View configure > Verify configure if settings are saved

- src/test/java/school/redrover/Pipeline14Test.java
TC_00.002.14 | Creating new item > Creating Pipeline
> Add Create Pipeline

- src/test/java/school/redrover/FreestyleProject16Test.java
https://trello.com/c/pBzqNbLq/454-tc0000119-creating-new-item-creating-freestyle-project
> TC_00.001.19 | Add testCreateFreestyleProject

- src/test/java/school/redrover/View4Test.java
https://trello.com/c/ixw89qTP/428-tc1000213-views-edit-view-jobs-can-be-added
> TC_10.002.14 Views > Edit view > Jobs can be added to list view_from main section link

- src/test/java/school/redrover/MultibranchPipeline3Test.java
> TC_05.001.01 | Multibranch pipeline>View Multibranch pipeline page>Sidebar>Visibility>See sidebar menu consist 10 tasks

- src/test/java/school/redrover/Pipeline9Test.java
https://trello.com/c/bMh2V9nX/442-tc0100110-freestyle-project-add-description
> TC_02.001.07 | add a Pipeline description

- src/test/java/school/redrover/FreestyleProject11Test.java
- src/test/java/school/redrover/FreestyleProjectRenameTest.java
https://trello.com/c/5JTqhrxB/444-tc0100206-item-sub-item-us-title
> TC_01.002.06 | Freestyle project > Rename project

- src/test/java/school/redrover/OrganizationFolder8Test.java
https://trello.com/c/R6yVLt9t/457-tc0000512-new-item-organization-folder-create-organization-folder-with-valid-name
> TC_00.005.07 | add testCreateOrganizationFolderWithValidName

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/zyIjtzTD/455-tc0100201-freestyleproject-rename-project-verify-redirection-to-the-project-page-after-renaming
> TC_01.002.01 |  Verify redirection to the project page after renaming

- src/test/java/school/redrover/View4Test.java
https://trello.com/c/3oYpcn28/461-tc1000215-views-edit-view-jobs-can-be-added-to-list-view
> TC_10.002.15 Views > Edit view > Jobs can be added to list view

- src/test/java/school/redrover/OrganizationFolder8Test.java
https://trello.com/c/tTukjZEP/471-tc0000508-new-item-organization-folder-new-organization-folder-appeared-on-dashboard
> TC_00.005.08 | add testNewOrganizationFolderAppearedOnDashboard

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/tsJ3wiDL/439-tc0100304-freestyle-project-delete-project
> TC_01.003.04 | Freestyle project > Delete project

- src/test/java/school/redrover/Folder11Test.java
https://trello.com/c/sClZ2Jot/465-tc0400207-folder-move-folder-to-folder
> TC_04.002.07 Folder > Test move nested folder to main folder

- src/test/java/school/redrover/NodeTest.java
https://trello.com/c/QnPVznj7/463-tc1500503-nodes-configure-node-add-description
> TC_15.005.03 add testAddDescription

- src/test/java/school/redrover/Nodes2Test.java
https://trello.com/c/NVYevBo7/449-tc15009-nodes-create-new-node-from-jenkins-main-panel 
create new node from main screen
> TC_15.001.11 Create new node from main panel

- src/test/java/school/redrover/FreeStyleProject88Test.java
https://trello.com/c/SJbdppI9/482-us01001-freestyle-project-add-description
> TC_01.001.09 | Freestyle project > Add description

- src/test/java/school/redrover/Pipeline26Test.java
> TC_00.002.21| Creating new item > Add Test Creating Pipeline

- src/test/java/school/redrover/HeaderTest.java
changed test for verifying return for Main page from Main menu items pages by clicking Jenkins Logo
https://trello.com/c/3DSATDd2/413-rf1400102-header-return-to-the-dashboard-page-with-one-click
> RF_14.001.02

- src/test/java/school/redrover/NodeTest.java
https://trello.com/c/uBSSaHHu/485-tc1500504-nodes-configure-node-add-label
> TC_15.005.04 add testAddLabel

- src/test/java/school/redrover/FreestyleProject13Test.java
https://trello.com/c/5PX5v5EN/479-rf0100109-freestyle-project-add-description
> RF_01.001.09 | Freestyle project > Add description

- src/test/java/school/redrover/View2Test.java
https://trello.com/c/qHcaHn7m/488-tc1000217-views-edit-view-verify-the-view-can-be-renamed
> TC_10.002.17 | Views > Edit view > Verify the view can be renamed

- src/test/java/school/redrover/View4Test.java
https://trello.com/c/KkX1e9s3/446-tc1000216-views-edit-view-columns-can-be-ordered
> TC_10.002.16 Views > Edit view > Columns can be ordered

- src/test/java/school/redrover/Pipeline9Test.java
https://trello.com/c/ncFFdqen/462-tc0000000-item-sub-item-us-title
> TC_02.001.08 | Verify pipeline stage view before build

- src/test/java/school/redrover/FreestyleProject13Test.java
https://trello.com/c/JznEXw7y/493-tc0100112-freestyle-project-edit-the-existing-description
> TC_01.001.12 | Freestyle project > Edit the existing description

- src/test/java/school/redrover/Pipeline26Test.java
> TC_02.007.12| Pipeline > Add Rename project Test

- src/test/java/school/redrover/OrganizationFolder5Test.java
https://trello.com/c/zfqvoDea/501-tc0600404-organization-folder-disable-organization-folder-verify-message-after-job-is-disabled
> TC_06.004.04 | Organization folder > Disable Organization folder > Verify Organization folder is disabled

- src/test/java/school/redrover/FreestyleProject6Test.java
> TC_01.001.015 | Freestyle project > Add description

- src/test/java/school/redrover/BuildHistory2Test.java
- src/test/java/school/redrover/Folder7Test.java
https://trello.com/c/pMDrKudV/494-ts0800103-build-history-view-the-build-history
> TS_08.001.03 Check date and month build history

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/2wBXc5Y9/452-tc0100614-freestyle-project-configure-general-settings
> TC_01.006.14 | The tooltip message is displayed near the checkbox 'Execute concurrent builds if necessary'.

- src/test/java/school/redrover/NewUserTest.java
https://trello.com/c/Pe5znE9D/496-tc0900102-manage-jenkins-create-user-with-valid-data
> TC_09.001.02 | Manage Jenkins > Create User with valid data

- src/test/java/school/redrover/OrganizationFolder3Test.java
https://trello.com/c/fhN2yUyo/504-tc06004-organization-folder-disable-organization-folder
> TC_06.004 | Disable Organization folder

- src/test/java/school/redrover/FreestyleProject6Test.java
> TC_01.001.016 | Freestyle project > Edit description

- src/test/java/school/redrover/Pipeline9Test.java
https://trello.com/c/S9S4G9kA/478-tc0200110-pipeline-view-pipeline-page-verify-permalinks-section-after-a-build
> TC_02.001.10 | Pipeline > View pipeline page > Permalinks section contains info about builds

- src/test/java/school/redrover/Folder12Test.java
https://trello.com/c/7V3fhJUl/431-tc0400302-folder-create-a-new-job-inside-a-folder
> TC_04.003.02  Create a new freestyle project inside a folder

- src/test/java/school/redrover/FreestyleProject18Test.java
> TC_00.001.18 | Freestyle Project> Create Freestyle project with valid name

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/E5tcTwt0/458-rf0500201-multibranch-pipeline-sub-item-us-title
> TC_05.002.1 Multibranch pipeline refactor

- src/test/java/school/redrover/FreestyleProject16Test.java
https://trello.com/c/DafQLtjC/456-tc0100107-freestyle-project-add-description
> TC_01.001.07 | add testAddDescriptionToFreestyleProject + refactoring

- src/test/java/school/redrover/UserTest.java
https://trello.com/c/lxhmvKOB/459-tc1300105-user-create-user
> TC_13.001.05 Add Create User

- src/test/java/school/redrover/FreestyleProject14Test.java
https://trello.com/c/aM9bSSLB/359-tc0000113-creating-new-item-creating-freestyle-project
> Refactiring

- src/test/java/school/redrover/FreestyleProjectTest.java
> TC_01.006.15 | Freestyle project > Configure General settings > Verify the set number of builds are kept

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/ECVvBaVR/460-tc01006006-freestyle-project-configure-general-settings-the-number-of-days-to-keep-builds-must-be-positive
> TC_01.006.006 |The number of 'Days to keep builds' must be positive.

- src/test/java/school/redrover/FolderTest.java
Add 2 tests to verify Folder is not created without folder name
https://trello.com/c/FkY95vDv
> TC_00.007 | Creating new item > Folder item >Verify Folder is not created with empty Folder_name

- src/test/java/school/redrover/FreestyleProject17Test.java
TC. US_00.001.17 | Creating new item > Creating Freestyle project > With valid name
https://trello.com/c/WdR4W4nE/429-us0000117-creating-new-item-creating-freestyle-project-with-valid-characters
> TC. US_00.001.17 | Creating new item

- src/test/java/school/redrover/Folder6Test.java
https://trello.com/c/Trz5Jhfz/490-tc0000506-create-organization-folder-with-valid-name
> Re/tc 00.005.06

- src/test/java/school/redrover/FreestyleProject11Test.java
https://trello.com/c/qZzTttpO/523-rftc0100206-freestyle-project-rename-project
> RF_01.002.06 | Freestyle project > Rename project

- src/test/java/school/redrover/NewUser2Test.java
TC_09.001.05 | Manage Jenkins>Create user> The created user is displayed in the users table
> TC_09.001.05 | The created user is displayed in the users table

- src/test/java/school/redrover/NodeTest.java
https://trello.com/c/grgVEhl4/529-tc1500506-nodes-configure-node-set-incorrect-number-of-executors
> TC_15.005.04 add testSetIncorrectNumberOfExecutes

- src/test/java/school/redrover/MulticonfigurationProject3Test.java
https://trello.com/c/lPYg4Ac7/527-tc00001-us00003-creating-new-item-creating-multiconfiguration-project
> TC_00.003.05 add test creating multiconfiguration project

- src/test/java/school/redrover/NodeTest.java
https://trello.com/c/AuzTEcSk/539-tc1500507-nodes-configure-node-set-enormous-number-of-executors
> TC_15.005.07 add testSetEnormousNumberOfExecutes

- src/test/java/school/redrover/Breadcrumb2Test.java
- src/test/java/school/redrover/Folder13Test.java
- src/test/java/school/redrover/OrganizationFolderRenameTest.java
Folder > Create a new job inside a folder
> TC_04.003.03 | Folder > Create a new job inside a folder

- src/test/java/school/redrover/MultibranchPipeline4Test.java
> TC_05.002.03 | Multibranch pipeline > Rename Multibranch pipeline > Verify that the Multibranch pipeline could be renamed through the sidebar

- src/test/java/school/redrover/Pipeline1Test.java
https://trello.com/c/qG5RTwui/536-tc00002023-creating-new-item-creating-pipeline
> TC_00.002.023 Creating new item > Creating Pipeline

- src/test/java/school/redrover/ManageJenkinsTest.java
https://trello.com/c/UdvjAafJ/371-tc0900103-manage-jenkins-create-user-create-user-with-valid-data
> TC_09.001.03 | Add create user with valid data

- src/test/java/school/redrover/MulticonfigurationProject3Test.java
https://trello.com/c/WQkIJxZ1/548-rf0000000-tc0000305-creating-new-item-creating-multiconfiguration-project
> RF_00.003.05 | Creating new item > Creating Multiconfiguration project

- src/test/java/school/redrover/MultibranchPipeline2Test.java
https://trello.com/c/Rm24BIo2/531-tc0000604-create-multibranch-pipeline-from-existing-multibranch-pipeline
> TC_00.006.04 | Create Multibranch Pipeline from existing Multibranch Pipeline

- src/test/java/school/redrover/FreestyleProject11Test.java
https://trello.com/c/ABXn8dzD/549-rf0100207-freestyle-project-rename-project
> RF_01.002.07 | Freestyle project > Rename project

- src/test/java/school/redrover/Pipeline1Test.java
https://trello.com/c/pWn62PjR/544-tc02005012-pipeline-delete-project
> TC_02.005.012 | Pipeline> Delete project

- src/test/java/school/redrover/MulticonfigurationProjectTest.java
> TC_03.001 | Multiconfiguration project > Add description

- src/test/java/school/redrover/FreestyleProject19.java
- src/test/java/school/redrover/FreestyleProject19Test.java
Add test for create creating Freestyle project
> TC_00.001.18 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/DeleteFreestyleProjectTest.java
https://trello.com/c/mVMBcVUH/438-tc01003005-freestyle-project-delete-project
> TC_01.003.005 | Freestyle project > Delete project_ref

- src/test/java/school/redrover/Folder11Test.java
https://trello.com/c/sClZ2Jot/465-tc0400207-folder-move-folder-to-folder
Optimizing the code
> TC_04.002.07 | Optimizing the code

- src/test/java/school/redrover/MultibranchPipeline4Test.java
> TC_05.002.05 | Multibranch pipeline > Rename Multibranch pipeline > Verify the renaming results are displayed in the in the breadcrumb trail

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/vim0cYvl/502-tc0100617-freestyle-project-execute-concurrent-builds-if-necessary-checkbox-ticked-in-general-configure
> TC_01.006.17 | Freestyle project"GitHub project" checkbox ticked in General Configure

- src/test/java/school/redrover/FreestyleProject19Test.java
https://trello.com/c/l778yulL/538-tc0000119-creating-new-item-creating-freestyle-project
> TC_00.001.19 | Creating new item > Creating Freestyle project

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/hhxSLmiw/412-tc0100109-freestyleproject-edit-the-existing-description
> TC_01.001.09 | FreestyleProject > Edit the existing description

- src/test/java/school/redrover/Pipeline1Test.java
https://trello.com/c/zmITgTwX/547-tc0200111-pipeline-checking-pipeline-buildnow-launch
> TC__02.001.05 | Pipeline > Checking Pipeline BuildNow Launch

- src/test/java/school/redrover/MultibranchPipeline3Test.java
> TC_05.001.02 | Multibranch pipeline>View Multibranch pipeline page>Sidebar>Visibility>See the names of tasks from sidebar menu on the left

- src/test/java/school/redrover/MultibranchPipeline4Test.java
> TC_05.002.06 | Multibranch pipeline > Rename Multibranch pipeline > Verify the renaming results are displayed in the dashboard

- src/test/java/school/redrover/Folder6Test.java
https://trello.com/c/P17ECvjo/557-tc0000517-delete-organization-folder-check-warning-message
> TC_00.005.17 | Delete Organization Folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/1IeILZul/525-tc0100305-freestyle-project-delete-existing-project
> TC_01.003.05 | Freestyle project > Delete existing project from side menu on Project Status page

- src/test/java/school/redrover/Pipeline1Test.java
https://trello.com/c/WI0F3rKg/566-tc02001011-view-pipeline-page-add-description
> TC_02.001.011 | View pipeline page >Add description

- src/test/java/school/redrover/Pipeline13Test.java
https://trello.com/c/kXbBr82G/410-tc0200711-pipeline-rename-projectcheck-renaming-the-project-on-the-drop-down-menu-near-the-project-name-on-the-dashboard
> TC_02.007.11 | Pipeline > Rename project>Check renaming the project on the drop-down menu near the project name on the Dashboard

- src/test/java/school/redrover/FreestyleProject20Test.java
https://trello.com/c/xRFWQEKb/569-tc0100110-freestyleproject-delete-the-existing-description
added some tests in one class TC_01.001.02, TC_01.001.09
> TC_01.001.10 | FreestyleProject > Delete the existing description

- src/test/java/school/redrover/Folder3Test.java
https://trello.com/c/da1ZhxIh/360-tc0400205-move-folder-to-folder-from-drop-down-menu
> TC_04.002.05 | Move Folder to Folder from drop-down menu

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/JjFAMpbp
Verify tool-tip description on pipeline configure page complies with check-boxes text
> TC_02.004.07 | Pipeline > View configure > Verify tool-tip description complies with check-boxes text

- src/test/java/school/redrover/NewUser1Test.java
https://trello.com/c/eaVBptGC/570-tc0900107-manage-jenkins-create-user
> TC_09.001.07 | Create a new User

- src/test/java/school/redrover/FreestyleProject1Test.java
Add local variables - name and description.
> RF_01.006.14 | FreestyleProject > Configure General settings > Select This project is parameterized checkbox > Add Boolean Parameter

- src/test/java/school/redrover/MultibranchPipeline2Test.java
https://trello.com/c/05OROz8r/545-tc0000605-create-multibranch-pipeline-from-non-existing-multibranch-pipeline
> TC_00.006.05 | Create Multibranch Pipeline from non-existing Multibranch Pipeline

- src/test/java/school/redrover/FolderNew2Test.java
https://trello.com/c/O4lPP6Ny/530-tc0000713-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.13 | Creating new item > Folder item > Creating a new Folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/DTxTybNl/541-tc0000120-creating-new-item-creating-freestyle-project-from-existing-freestyle-project
> TC_00.001.20 | Creating new item > Creating Freestyle project from existing Freestyle project

- src/test/java/school/redrover/FreestyleProject4Test.java
https://trello.com/c/ZdZ7cMNT/441-tc0100204-freestyle-project-rename-project
> TC_01.002.04 | Freestyle project > Rename project

- src/test/java/school/redrover/ManageJenkinsTest.java
https://trello.com/c/gVlzNKHV/580-tc0900107-manage-jenkins-user-delete-user
> TC_09.001.07 | Add delete user

- src/test/java/school/redrover/FreestyleProject4Test.java
https://trello.com/c/EtBmymm0/586-tc01003-freestyle-project-delete-project
> TC_01.003.07 | Freestyle project > Delete project

- src/test/java/school/redrover/Pipeline1Test.java
https://trello.com/c/bP4GpdEH/582-tc02001012-view-pipeline-page-delete-description-in-configuration
> TC_02.001.012 | View pipeline page >Delete description in Configuration

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/ophhTRMQ/511-tc0100202-freestyleproject-rename-project-verify-the-message-no-name-is-specified-below-new-name-field-when-new-name-field-is-cl
> TC_01.002.02 | Verify the message “No name is specified” below New Name field when New Name field is clear

- src/test/java/school/redrover/Folder5Test.java
https://trello.com/c/p6MW8wc6/589-tc0400504-folder-add-edit-description
> TC_04.005.04 | Folder > Add description

- src/test/java/school/redrover/Folder3Test.java
https://trello.com/c/uxVb9jKZ/571-tc0400306-create-a-new-job-inside-a-folder
> TC_04.003.06 | Create a new job inside a folder

- src/test/java/school/redrover/CreateUserTest.java
https://trello.com/c/rO4s95zV/336-tc0900101-manage-jenkins-create-user-create-user-with-all-the-fields-filled-in-using-a-valid-data
> TC_09.001.01 | CreateUser with all the fields filled in using a valid Data

- src/test/java/school/redrover/DeleteUserTest.java
https://trello.com/c/e7CXSIvL/594-tc1300502-user-delete-user
> TC_13.005.02 add testDeleteUser

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/Ctn2mRz1/559-tc0101402-freestyle-project-view-permalinks-for-builds-delete-permalinks-on-projects-status-page
> TC_01.014.02 | Delete Permalinks on project's Status page

- src/test/java/school/redrover/Breadcrumb4Test.java
https://trello.com/c/of8tHSf4/563-tc1100203-breadcrumb-breadcrumb-dropdown-menu-return-to-home-page-when-clicking-on-dashboard-in-breadcrumb
> "TC_11.002.03 |Return to home page when clicking on "Dashboard" in Breadcrumb"

- src/test/java/school/redrover/Folder9Test.java
https://trello.com/c/J99JTxPc/606-us00007-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.04 | Creating new item > Folder item > Creating a new Folder >Verify subfolder is displayed in the breadcrumbs

- src/test/java/school/redrover/Nodes3Test.java
https://trello.com/c/Cx8n7KLP/605-tc15001-nodes-create-new-node-from-manage-jenkins
> TC_15.001.12

- src/test/java/school/redrover/OrganizationFolder9Test.java
https://trello.com/c/KKiK3X5n/596-tc0600305-organization-folder-rename-organization-folder-from-drop-down-list
> Ms/tc 06.003.05

- src/test/java/school/redrover/Footer11Test.java
https://trello.com/c/Qu4etNJp/592-tc1200111-footer-jenkins-version-viewing-the-jenkins-version
> TC_12.001.11 | Footer. Jenkins version

- src/test/java/school/redrover/Pipeline10Test.java
https://trello.com/c/RppRxJHe/550-tc0200509-pipeline-delete-project
> Tc 02.005.09 pipeline delete2

- src/test/java/school/redrover/HeaderTest.java
[TC_14.001.04 | Header > Return to the dashboard page with one click on Jenkins Logo image](https://trello.com/c/ujKwn5EI)
> TC_14.001.04 | Header > Return to the dashboard page

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/HOgEN53R/595-tc0100216-freestyle-project-rename-project-entering-unsafe-characters
> TC_01.002.16 | Entering unsafe characters

- src/test/java/school/redrover/RenameNode3Test.java
https://trello.com/c/lIBWjTNx/608-tc1500203-nodes-rename-node
> TC_15.002.03 | Rename node

- src/test/java/school/redrover/RestApiLink3Test.java
https://trello.com/c/8aEwN5er/612-tc1200204-footer-rest-api-link-visibility-and-clickability
> TC_12.002.04 | Footer > REST API link > Visibility and clickability

- src/test/java/school/redrover/MulticonfigurationProjectTest.java
https://trello.com/c/Guys3L3i
https://trello.com/c/nnid3dr8
> TS_03.001 | Multiconfiguration project > Edit and Delete description

- src/test/java/school/redrover/View3Test.java
https://trello.com/c/doIQ0RHU/309-tc1000208-views-edit-view-verify-the-job-could-be-added-to-the-view
> TC_10.002.08 | Views > Edit view > Verify the job could be added to the View

- src/test/java/school/redrover/CreateUserTest.java
https://trello.com/c/uB2fPB4L/591-tc0900102-manage-jenkins-create-user-create-user-with-empty-name
> TC_09.001.02 | Create User with empty Name

- src/test/java/school/redrover/View3Test.java
https://trello.com/c/N2owwwt1/310-tc1000209-views-edit-view-verify-associated-job-is-shown-on-the-dashboard-when-the-view-is-selected
> TC_10.002.09 | Views > Edit view > Verify associated job is shown on the Dashboard when the View is selected

- src/test/java/school/redrover/MulticonfigurationProject4Test.java
https://trello.com/c/A3w5CrZR/621-tc0000307-creating-new-item-creating-multiconfiguration-project
> TC_00.003.07 | Creating new item > Creating Multiconfiguration project

- src/test/java/school/redrover/Pipeline15Test.java
https://trello.com/c/cgiRvhCG/620-tc0000224-creating-new-item-creating-pipeline
> TC_00.002.24 | Creating new item > Creating Pipeline

- src/test/java/school/redrover/MulticonfigurationProject11Test.java
TC_00.003.09
https://trello.com/c/FcgH6YiE/626-tc0000309-creating-new-item-creating-multiconfiguration-project-by-clicking-new-item-in-the-left-panel
TC_00.003.08
https://trello.com/c/Z2m5ch7l/625-tc0000308-creating-new-item-creating-multiconfiguration-project-no-projects-were-created-prior
> Created tests to create MC project 

- src/test/java/school/redrover/FolderTest.java
> TC_04.006.01 | Folder > Configuration > General settings > Add Display Name

- src/test/java/school/redrover/MulticonfigurationProject4Test.java
https://trello.com/c/1tcbFM9h/627-tc0300102-multiconfiguration-project-add-description
> TC_03.001.02 | Multiconfiguration project > Add description

- src/test/java/school/redrover/Folder5Test.java
https://trello.com/c/In1JVpO8/590-tc0400505-folder-delete-description
> TC_04.005.05 | Folder > Delete description

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/sAqJFJW9/615-tc0500105-multibranch-pipeline-view-multibranch-pipeline-page-sidebar-visibility-clickability-redirection-check-all-task-link-te
> TC_05.001.05 | Check all task link text in the sidebar

- src/test/java/school/redrover/OrganizationFolder8Test.java
https://trello.com/c/2uLVkn4i/628-tc0000518-new-item-organization-folder-create-organization-folder-with-long-name
> TC_00.005.18 | add testCreateOrganizationFolderWithLongName

- src/test/java/school/redrover/OrganizationFolder8Test.java
https://trello.com/c/QgXrXbuy/629-tc0000518-new-item-organization-folder-create-organization-folder-with-existing-name
> TC_00.005.19 | add testCreateOrganizationFolderWithExistingName

- src/test/java/school/redrover/OrganizationFolderTest.java
> RF_01.005.11 | New Item > Organization Folder > The created Organization Folder is located in the projects table on Dashboard page

- src/test/java/school/redrover/Folder11Test.java
- src/test/java/school/redrover/FreestyleProject15Test.java
https://trello.com/c/1F3hBz3q/604-tc0100120-freestyleproject-edit-the-existing-description
> TC_01.001.20 | FreestyleProject > Edit the existing description

- src/test/java/school/redrover/Folder2Test.java
https://trello.com/c/88lBpoA5/635-tc0400602-folder-configuration-general-settings-add-description
> TC_04.006.02

- src/test/java/school/redrover/FreestyleProject13Test.java
https://trello.com/c/In6ZI5pO/634-tc0000715-creating-new-item-folder-item-creating-a-new-folder
> TC_00.007.15 | Creating new item > Folder item > Creating a new Folder

- src/test/java/school/redrover/Folder14Test.java
- src/test/java/school/redrover/Folder2Test.java
https://trello.com/c/IIlfcBfV/636-tc0400603-folder-configuration-general-settings-add-library-name
> TC_04.006.03| Folder > Configuration > General settings > Check Preview link

- src/test/java/school/redrover/View3Test.java
https://trello.com/c/YdbMUTZd/311-tc1000210-views-edit-view-verify-a-new-column-could-be-added-to-the-view
> TC_10.002.10 | Views > Edit view > Verify a new column could be added to the View

- src/test/java/school/redrover/FreestyleProject6Test.java
https://trello.com/c/Gp7dehWM/432-tc0101504-freestyle-project-move-project
> TC_01.015.04 | Freestyle project > Move Project

- src/test/java/school/redrover/FreestyleProject21Test.java
https://trello.com/c/KNNktDuG/425-tc0100701-freestyle-project-configure-advanced-settings-visibility-of-help-description-quiet-period
> Add TC_01.007.01

- src/test/java/school/redrover/CreateUserTest.java
https://trello.com/c/qcJE2uvg/609-tc0900107-manage-jenkins-create-user%D1%81reate-user-using-different-values-in-the-password-and-confirm-password-fields
> TC_09.001.07 | Create user using different Password and Confirm password

- src/test/java/school/redrover/FreestyleProject21Test.java
- src/test/java/school/redrover/FreestyleProject22Test.java
https://trello.com/c/clNPHk44/633-tc0000122-create-freestyle-project-using-valid-name
> TC_00.001.22 | Create Freestyle Project > Using valid name

- src/test/java/school/redrover/MulticonfigurationProject6Test.java
https://github.com/RedRoverSchool/JenkinsQA_07/compare/OF_Multiconfiguration?expand=1
> TC_00.003.05 | Creating new item > Creating Multiconfiguration project

- src/test/java/school/redrover/View3Test.java
https://trello.com/c/8lIWPizY/312-tc1000211-views-edit-view-verify-a-column-could-be-deleted-from-the-view
> TC_10.002.11 | Views > Edit view > Verify a column could be deleted from the View

- src/test/java/school/redrover/MulticonfigurationProject4Test.java
https://trello.com/c/NKy5ORsH/640-tc0300103-multiconfiguration-project-edit-description
> TC_03.001.03 | Multiconfiguration project > Edit description

- src/test/java/school/redrover/FreestyleProjectVDTest.java
> TC_01.014.003 | Freestyle project > View Permalinks for builds > Verify whether is Workspace on Built-In Node after build

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/Cru3NCVS/600-tc0100702-freestyle-project-configure-advanced-settings-visibility-of-help-description-quiet-period
> TC_01.007.02

- src/test/java/school/redrover/FreestyleProject32Test.java
https://trello.com/c/PiYFYyH0/649-tc0000132-creating-new-item-creating-freestyle-project
> TC_00.001.32 | Add create FreestyleProject32Test

- src/test/java/school/redrover/FreestyleProject27Test.java
https://trello.com/c/vBRvO7jI/648-tc0000127-creating-new-item-creating-freestyle-project
> TC_00.001.27 Create FreeStyle project

- src/test/java/school/redrover/Folder15Test.java
https://trello.com/c/81vmpgAB/646-tc0400307-folder-create-a-new-job-inside-a-folder
>     TC_04.003.07 | Folder > Create a new job inside a folder

- src/test/java/school/redrover/FreestyleProject17Test.java
TC_01.001.17 | Freestyle project > Add description
https://trello.com/c/kZsA6LyI/639-tc0100117-freestyle-project-add-description
> TC_01.001.17 | Freestyle project > Add description

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/7UhtIhis/641-tc0500601-multibranch-pipeline-delete-multibranch-pipeline-from-the-sidebar-on-the-multibranch-pipeline-page
> TC_05.006.01 Multibranch pipeline Delete Multibranch pipeline from sidebar on the existing Multibranch pipeline page

- src/test/java/school/redrover/NewItemTest.java
https://trello.com/c/eTKrFP0z/658-tc0000401-new-item-%D1%81reate-a-new-item-from-existing-job-verify-the-create-new-item-from-existing-job-field-displayed-on-new-item
> TC_00.004.01 | Verify the 'Create New Item from Existing Job' field displayed on "New Item" page when at least one job exists

- src/test/java/school/redrover/NewItemTest.java
https://trello.com/c/aohqDLkU/662-tc0000402-new-item-%D1%81reate-a-new-item-from-existing-job-verify-the-create-new-item-from-existing-job-section-is-not-displayed-on
> TC_00.004.02| Verify the 'Create New Item from Existing Job' section is NOT displayed on "New Item" page when there is no any item created

- src/test/java/school/redrover/MulticonfigurationProject6Test.java
https://trello.com/c/asnUL6oW/655-err0000305-creating-new-item-creating-multiconfiguration-project
> ERR_00.003.05 |Creating new item > Creating Multiconfiguration project

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/pL1rSqbL/498-tc0100616-freestyle-project-configure-general-settings-add-build-step
> Ech/tc 01.006.16

- src/test/java/school/redrover/MulticonfigurationProjectTest.java
https://trello.com/c/guQvsBIr/63-tc0000303-creating-new-item-creating-multiconfiguration-project-create-multiconfiguration-project-with-dublicate-name
> TC_00.003.03 Create Multiconfiguration project with dublicate name

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/mAx9Poat/665-tc0000310-creating-new-item-creating-multiconfiguration-project
> TC_00.003.10 | Creating new item > Creating Multiconfiguration project

- src/test/java/school/redrover/FreestyleProject22Test.java
https://trello.com/c/wwPgdW3g/661-tc0000124-creating-freestyle-project-using-invalid-after-name
> TC_00.001.24 | Creating Freestyle project > using invalid after name

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/mOJr9zA9/667-tc0100622-freestyle-project-configure-general-settings-github-edited-label-appears
> TC_01.006.22 | Freestyle project > Configure General settings > GitHub > Edited label appears

- src/test/java/school/redrover/Folder10Test.java
https://trello.com/c/9i0foHGN/664-rf0000706-creating-new-item-folder-item-creating-a-new-folder
> RF_00.007.06 change locators

- src/test/java/school/redrover/NodesTest.java
https://trello.com/c/XK7AIkjI/602-tc1500402-nodes-node-status-update-offline-reason
> TC_15.004.02 add Update Offline Reason test

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/MDgEjCIx/675-tc0100402-freestyle-project-disable-project
> TC_01.004.02 | Freestyle project > disable project

- src/test/java/school/redrover/BuildHistory3Test.java
https://trello.com/c/n9AhXbbw/588-tc0800104-build-history-view-the-build-history-icon-legend-clickable-and-parameters-are-visible
> TC_08.001.04 | Build history > View the build history > Icon legend

- src/test/java/school/redrover/Nodes4Test.java
https://trello.com/c/5klehUYJ/327-tc15008-nodes-create-new-node-sees-node-in-table-of-nodes-sort-by-name
> TC_15.008 | Nodes > Create new node > Sees node in table of nodes > Sort by name in reverse order

- src/test/java/school/redrover/Folder15Test.java
https://trello.com/c/FEb93BsU/659-tc0400112-folder-rename-folder
> TC_04.001.12 | Folder > Rename Folder

- src/test/java/school/redrover/Nodes2Test.java
added test about renaming existing node
https://trello.com/c/c0RLSOjz/670-tc1500204-nodes-rename-node
> TC_15.002.04 | Nodes > Rename node

- src/test/java/school/redrover/NewItemTest.java
https://trello.com/c/YlcSEZ05/681-tc0000405-new-item-%D1%81reate-a-new-item-from-existing-job-verify-autocomplete-functionality-of-copy-from-field-when-any-item-exists
> TC_00.004.05 | Verify Autocomplete functionality of 'Copy From' field when any item exists

- src/test/java/school/redrover/Folder15Test.java
https://trello.com/c/zAuQP9mz/680-tc0400506-folder-add-description
> TC_04.005.06 | Folder > Add description

- src/test/java/school/redrover/Pipline27Test.java
https://trello.com/c/FPlSjylk/510-tc00002-creating-new-item-creating-pipeline
> Jenkins test, TC_00.002 | Creating new item > Creating Pipeline

- src/test/java/school/redrover/FreestyleProject6Test.java
> TC_01.003.13 | Freestyle project > Delete project > Verify the deleted freestyle project no longer exists on the dashboard

- src/test/java/school/redrover/FreestyleProject6Test.java
> TC_01.004.12 | Freestyle project > Disable project > Verify the message appears after the project is disabled on the project page

- src/test/java/school/redrover/Folder15Test.java
https://trello.com/c/UTogufCn/683-tc0400507-folder-edit-description
> TC_04.005.07 | Folder > Edit description

- src/test/java/school/redrover/Pipeline16Test.java
https://trello.com/c/t04JMy4J/676-tc0000216-creating-new-item-creating-pipeline
> TC_00.002.16 Create Pipeline

- src/test/java/school/redrover/FreestyleProject13Test.java
https://trello.com/c/pqy0a1KB/638-tc0101503-freestyle-project-move-project
> TC_01.015.03 | Freestyle project > Move Project

- src/test/java/school/redrover/NewUserTest.java
https://trello.com/c/lErv62dH/685-rf0900102-manage-jenkins-create-user
> RF_09.001.02 Manage Jenkins > Create User

- src/test/java/school/redrover/Node3Test.java
https://trello.com/c/JEhbQqVc/682-tc1500113-nodes-create-new-node-from-manage-jenkins
> TC_15.001.13 | Nodes > Create new Node from Manage Jenkins

- src/test/java/school/redrover/FreeStyleProject24Test.java
https://trello.com/c/csPwpeRX/689-us01001-freestyle-project-add-description
> US_01.001| Freestyle project > Add description

- src/test/java/school/redrover/User2Test.java
[https://trello.com/c/iDoFnL4G/691-tc1300106-user-create-user-log-in-with-new-users-credentials](https://trello.com/c/iDoFnL4G/691-tc1300106-user-create-user-log-in-with-new-users-credentials)
> TC_13.001.06 | User > Create User > Log in with new user's credentials

- src/test/java/school/redrover/MulticonfigurationProject3Test.java
https://trello.com/c/m9Tp6QOX/574-tc0000306-creating-new-item-creating-multiconfiguration-project
> TC_13.001.06 Add Create Multiconfiguration Project

- src/test/java/school/redrover/User2Test.java
[https://trello.com/c/g5gt46LG/693-tc1300503-user-delete-user-user-cant-log-in](https://trello.com/c/g5gt46LG/693-tc1300503-user-delete-user-user-cant-log-in)
> TC_13.005.03 | User > Delete user > User can't log in

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/WZ5KnRUb/701-tc0100623-freestyle-project-configure-general-settings-description-preview-appears
Add:
1. TC_01.006.23 test for Description preview appears
2. hoverClick method
3. hoverClickInput method
> TC_01.006.23 | Freestyle project > Configure General settings > Description > Preview appears

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/W1VPOziv/704-tc0100624-freestyle-project-configure-general-settings-description-preview-hides
> TC_01.006.24 | Freestyle project > Configure General settings > Description > Preview hides

- src/test/java/school/redrover/RestApiLink5Test.java
- src/test/java/school/redrover/RestApiLinkTest5.java
https://trello.com/c/pUmJHSms/707-tc1200205-footer-rest-api-link-visibility-and-clickability
> TC_12.002.05  | Footer > REST API link > Visibility and clickability

- src/test/java/school/redrover/Multiconfigurationproject12Test.java
https://trello.com/c/gddkn7zm/699-tc03001061-multiconfiguration-project-add-description-while-creation-project
https://trello.com/c/K76pjUPW/700-tc03001062-multiconfiguration-project-add-description-on-the-multi-configuration-project-page
https://trello.com/c/V1I1ehgn/702-tc03001063-multiconfiguration-project-edit-description-on-the-multi-configuration-project-page
https://trello.com/c/rrr5jguD/703-tc03001064-multiconfiguration-project-delete-description-on-the-multi-configuration-project-page
> TC_03.001.06.1 | Multiconfiguration project > Add description

- src/test/java/school/redrover/User3Test.java
https://trello.com/c/fTVcOUeM/720-tc1300107-user-create-user
> TC_13.001.07 | User > Create User

- src/test/java/school/redrover/FreestyleProject16Test.java
https://trello.com/c/sCkqNiKx/715-tc0100111-freestyle-project-delete-project-description?filter=member:evgenysheykin
> TC_01.001.11 | add testDeleteProjectDescription

- src/test/java/school/redrover/User3Test.java
https://trello.com/c/ZDI7O6ES/721-tc1300304-user-configure-user
> TC_13.003.04 | User > Configure user

- src/test/java/school/redrover/Folder15Test.java
https://trello.com/c/U9GlBQgk/723-tc0400508-folder-delete-description
> TC_04.005.08 | Folder > Delete description

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/jn4IETbM
Refactor delete pipeline project: add explicit wait, dependsOnMethods; refactor methods createAPipeline, goMainPageByBreadcrumb
> RF_02.005.01 | Pipeline > Delete project > Verify delete project through the side panel

- src/test/java/school/redrover/Folder12Test.java
- src/test/java/school/redrover/NewUser1Test.java
https://trello.com/c/x7BDkyFg/719-rf0400201-folder-testsuser-tests-us04-us09
> RF_04.002.01 | Organized tests in folder12Test and NewUser1Test in order

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/dkeODkbk/728-tc0200408-pipeline-view-configure-verify-choice-parameter-can-be-set
> TC_02.004.08 | Pipeline > View configure > Verify Choice Parameter can be set

- src/test/java/school/redrover/FreestyleProject22Test.java
https://trello.com/c/eEpfATMz/727-rf0000100-refactoring-freestyleproject22test-dependsonmethods-getwait
> RF_00.001.00 | Refactoring FreestyleProject22Test > getWait

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/VAZhpSyG
Refactor testSaveSettingsWhileConfigure with Explicit wait, made some locators as constant
> RF_02.004.04 | Pipeline > View configure > Verify configure if settings are saved

- src/test/java/school/redrover/MulticonfigurationProject2Test.java
https://trello.com/c/feTYDzxT/724-tc0000312-creating-new-item-creating-multiconfiguration-project
https://trello.com/c/KvJf4X1l/672-tc0300105-multiconfiguration-project-add-description-add-and-see-a-description-on-the-multiconfiguration-status-page
> AL/TC_03.001.05, TC_00.003.12 _Multiconfiguration_projectCreate_Add_description

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/s7RQH1qO/730-rf0100201-freestyle-project
> RF_01.002.01 | Freestyle project > Rename project > Entering unsafe characters

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/rWFiVguT
Refactor testUnsavedSettingsWhileConfigure with Explicit wait, rename locators, make a local variable as a constant
> RF_02.004.05 | Pipeline > View configure > Verify configure if settings are unsaved

- src/test/java/school/redrover/User3Test.java
https://trello.com/c/PyhlFzFM/722-tc1300504-user-delete-user
> TC_13.005.04 | User > Delete user

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/c5HLGBCi/736-tc0500501-multibranch-pipeline-enable-multibranch-pipeline-enable-by-default
> TC_05.005.01 | Multibranch Pipeline > Enable Multibranch Pipeline > Enable By Default

- src/test/java/school/redrover/FolderTest.java
add new test
TC_04.003.08 | Folder > Create a new job inside a folder > Create Pipeline and verify deletion of Pipeline
https://trello.com/c/9k544MPs/740-tc0400308-folder-create-a-new-job-inside-a-folder-create-pipeline-and-verify-deletion-of-pipeline
> TC_04.003.08 | Folder > Create a new job inside a folder > Create Pipeline and verify deletion of Pipeline

- src/test/java/school/redrover/Folder5Test.java
https://trello.com/c/YawY5Igy/734-rf0400201-organized-tests-in-class-folder5test
> RF_04.002.01 | Organized tests

- src/test/java/school/redrover/ManageJenkinsTest.java
https://trello.com/c/lkhFgEUk/744-tc1300305-user-configure-user-add-user-description
> TC_13.003.05 | Add user description

- src/test/java/school/redrover/Footer4Test.java
https://trello.com/c/6fcKJmHl/745-tc1200406-footer-rest-api-link-visibility-and-clickability
> TC_12.004.06 | Footer > REST API link > Visibility and clickability

- src/test/java/school/redrover/ManageJenkinsTest.java
https://trello.com/c/NF8d70jj/746-rf0900103-manage-jenkins-create-user-create-user-with-valid-data
Tests in classes was organized in order using dependsOnMethods.
> RF_09.001.03 | connect tests together

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/bxpcxbgD
Refactor testStageViewAfterRunningSampleBuild, runHelloWorldBuildInPipeline  with Explicit wait, make fields static
> RF_02.001.06 | Pipeline > View pipeline page > Verify stage view section after configure with a build sample

- src/test/java/school/redrover/NodesAllTest.java
Create new node from Manage Jenkins part1
https://trello.com/c/mo64kf9b/717-tc1500115-nodes-create-new-node-from-manage-jenkins
> TC_15.001.15 Nodes Create new node from Manage Jenkins

- src/test/java/school/redrover/Folder3Test.java
https://trello.com/c/Bp5Q3czV/742-rf0400109-changes-in-class-folder3test
> RF_04.001.09 | Changes in class Folder3Test

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/hVWeF3kK
Remove Ignore, change a locator and a waiter
> RF_00.002.04 | Creating new item > Creating Pipeline > Verify creation of a pipeline from the side panel

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/G2ycVvCh/226-tc0100401-freestyle-project-enable-or-disable-project
> TC_01.004.01 | Enable or disable project

- src/test/java/school/redrover/Folder3Test.java
https://trello.com/c/Zhm0uZeE/755-rf0400205-item-sub-item-us-title
> RF_04.002.05 |  Folder > remove Ignores

- src/test/java/school/redrover/FreestyleProject9Test.java
откорректировала первый тест в соответствии с замечаниями.
> TC_00.001.09 | Creating Freestyle project. Refactoring.

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/GJigVxaP/756-rf0200111-pipeline-delete-sleep
> RF_02.001.11 | Pipeline > Delete sleep

- src/test/java/school/redrover/OrganizationFolder9Test.java
https://trello.com/c/COmoO0Wz/773-rf0000711-new-item-organization-folder-create-organization-folder-with-valid-name
> refactoring  00.005.21

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/7SeMj3Rh
RF_02.001 add dependsOnMethods, refactor testStageViewAfterRunningSampleBuild, testStageViewBeforeBuild with constant variables
> RF_02.001 | Pipeline > View pipeline page

- src/test/java/school/redrover/CreateNevViewTest.java
https://trello.com/c/A97ldEqk/777-rf1000102-views-create-new-view
> RF_10.001.02 | Views > Create new view

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/z1Q9tEKG/778-tc05004-multibranch-pipeline-disable-multibranch-pipeline
> TC_05.004.03 | Multibranch Pipeline > Disable Multibranch Pipeline > See a alert after disable Multibranch Pipeline

- src/test/java/school/redrover/OrganizationFolder9Test.java
> RF_06.003.05 | Organization folder > Rename Organization folder from drop down list

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/pcrWHsPm/750-tc0100111-freestyle-project-add-description-delete-the-existing-description
> TC_01.001.11 | Freestyle project > Add description > Delete the existing description

- src/test/java/school/redrover/FreestyleProject16Test.java
https://trello.com/c/kCf8HYl7/779-tc0100203-freestyle-project-rename-project-using-valid-name
> TC_01.002.03 | add testRenameProjectUsingValidName

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/chWDP10Q/782-rf01006006-configure-general-settings-days-to-keep-builds-the-error-message-not-a-positive-integer-is-displayed-when-negative-nu
> RF_01.006.006 |The error message “Not a positive integer“ is displayed

- src/test/java/school/redrover/FolderTest.java
> RF_04.006.01 | Folder > Configuration > General settings > Add Display Name

- src/test/java/school/redrover/CreateNevViewTest.java
https://trello.com/c/yek79Ld0/762-tc1000218-views-edit-viewrename-view
> TC_10.002.18 | Views > Edit view>Rename view

- src/test/java/school/redrover/CreateNevViewTest.java
https://trello.com/c/5cg8djdK/763-tc1000219-views-edit-viewadd-description
> TC_10.002.19 | Views > Edit view>Add description

- src/test/java/school/redrover/Folder16Test.java
- src/test/java/school/redrover/FreestyleProject2Test.java
https://trello.com/c/TSNcHCjo/768-tc0000716-creating-new-item-folder-item-creating-a-new-folder
> Changes|Creating new item > Folder item > Creating a new Folder

- src/test/java/school/redrover/CreateNevViewTest.java
https://trello.com/c/K62wncqV/764-tc1000220-views-edit-viewadd-jobs-to-the-view
> TC_10.002.20 | Views > Edit view>Add jobs to the view

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/4lErDzoy/780-tc0800105-build-history-view-the-build-history-tooltip-is-visible-in-table-link
> TC_08.001.05 | Build history > View the build history > Tooltip is visible in the "Time Since" section

- src/test/java/school/redrover/NodesDeleteTest.java
https://trello.com/c/Z0qLKGXZ/786-tc1500302-nodes-delete-node-check-alert-message
https://trello.com/c/WuxDu7bb/787-tc1500303-nodes-delete-node-cancel-to-delete
https://trello.com/c/MEYYRmuO/789-tc1500305-nodes-delete-node-from-agent-page
> TC_15.003.02, TC_15.003.03, TC_15.003.05 - Delete Node tests

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/C24SJRcy/794-rf0100305-dependencies-of-tests
> RF_01.003.05 | Dependencies of tests

- src/test/java/school/redrover/NodesAllTest.java
https://trello.com/c/rlBHlCuQ/739-tc1500508-nodes-configure-node-add-description with dependsOnMethods
> TC_15.005.08_Nodes_Configure node_Add description

- src/test/java/school/redrover/View4Test.java
Dependencies added, tests refactored
https://trello.com/c/mSmPpsvT/804-rf1000216-views-edit-view-columns-can-be-ordered
https://trello.com/c/Qn3nUfah/803-rf1000215-views-edit-view-jobs-can-be-added-to-list-view
https://trello.com/c/xB4A9hzX/802-rf1000214-views-edit-view-jobs-can-be-added-to-list-viewfrom-main-section-link
https://trello.com/c/MDoJDrsh/801-rf1000213-views-edit-view-view-can-be-renamed
https://trello.com/c/pubLvOyL/799-rf1000107-views-create-new-view
> RF_10.002.16 Views > Edit view > Columns can be ordered

- src/test/java/school/redrover/View2Test.java
https://trello.com/c/yGiPtBVB/800-tc1000304-views-delete-view-verify-the-view-is-deleted-from-the-dashboard
> TC_10.003.04 | Views > Delete view >Verify the view is deleted from the Dashboard

- src/test/java/school/redrover/MultibranchPipeline4Test.java
- src/test/java/school/redrover/OrganizationFolderTest.java
> RF_05.002.04 | Multibranch pipeline > Rename Multibranch pipeline 

- src/test/java/school/redrover/FreestyleProject7Test.java
RF- https://trello.com/c/1KQmCGBV/806-rf0101401-freestyle-project-item-view-permalinks-for-builds-verify-the-permalinks-are-displayed-after-clicking-build-now
> Remove sleep(), replace with waits

- src/test/java/school/redrover/User2Test.java
[https://trello.com/c/ZtR6fd3M/796-tc13001008-user-create-user-user-on-jenkins-own-user-database](https://trello.com/c/ZtR6fd3M/796-tc13001008-user-create-user-user-on-jenkins-own-user-database)
> TC_13.001.008 | User > Create User > User on Jenkin's own user database

- src/test/java/school/redrover/BuildHistory2Test.java
https://trello.com/c/Ko16Ab8Y/818-rf0800103-build-history-view-the-build-history
> RF_08.001.03 Refactoring

- src/test/java/school/redrover/NodeTest.java
RF_15.005 create new goToNodesPage(), clickConfigureNode(), renameNode() methods for most uses options. Code refactoring.
https://trello.com/c/2Z1cniUw/817-rf1500501-nodes-ref-nodetest-class
> RF_15.005 class NodeTest refactoring

- src/test/java/school/redrover/Folder3Test.java
https://trello.com/c/ushIzBke/798-tc0000522-create-an-organization-folder-with-an-invalid-name
> TC_00.005.22 | Creates an organization folder with an invalid name

- src/test/java/school/redrover/FreestyleProject6Test.java
https://trello.com/c/RL8ozYIa/816-tc0100120-freestyle-project-add-description-description-preview-displayed
> TC_01.001.20 | Freestyle project >Add description > Description preview displayed

- src/test/java/school/redrover/User4Test.java
https://trello.com/c/J4VFCk9z/820-tc1300109-user-create-user-verify-validation-messages-are-shown-if-create-user-form-is-applied-with-empty-fields
> TC_13.001.10 | User > Create User > Verify validation messages are shown if Create User form is applied with empty fields

- src/test/java/school/redrover/User2Test.java
[https://trello.com/c/FI92fvAL/814-tc1300307-user-configure-user-set-users-default-view](https://trello.com/c/FI92fvAL/814-tc1300307-user-configure-user-set-users-default-view)
> TC_13.003.07 | User > Configure user > Set User's default view

- src/test/java/school/redrover/CreateUser3Test.java
- src/test/java/school/redrover/User4Test.java
https://trello.com/c/YcJA2Q8E/674-tc0900111-manage-jenkins-create-userjenkins-opens-user-database-tab-with-required-fields-for-user-creation-after-clicking-create
> TC_09.001.11 | Manage Jenkins > Create User

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/S41Bj8dp/836-rf01006006-freestyle-project-configure-general-settings-refactoring-dependency-and-waits
> RF_01.006.006 |Refactoring dependency and waits

- src/test/java/school/redrover/ManageJenkinsTest.java
https://trello.com/c/wIFb265X/835-tc0900303-manage-jenkins-delete-user-login-as-a-remote-user
> TC_09.003.03 | Manage Jenkins > Delete User > Login as a remote user

- src/test/java/school/redrover/FreestyleProject13Test.java
https://trello.com/c/ZvPZZA71/838-rf0000101-organized-tests
> RF_00.001.01 | Organized tests

- src/test/java/school/redrover/Header2Test.java
https://trello.com/c/7PbdW1sx/823-tc1400201-header-search-box-verify-exact-match-search-functionality-for-an-existing-entity
> TC_14.002.01 | Header > Search box > Verify Exact Match Search Functionality for an Existing Entity

- src/test/java/school/redrover/Folder4Test.java
[https://trello.com/c/RIW08qCA/827-tc0000718-creating-new-item-folder-item-creating-a-new-folder](https://trello.com/c/RIW08qCA/827-tc0000718-creating-new-item-folder-item-creating-a-new-folder)
Add New test,  
Add dependencies and refactoring for old tests
> TC_00.007.18 | Creating new item > Folder item > Creating a new Folder

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/pL1rSqbL/498-tc0100621-freestyle-project-configure-general-settings-add-build-step
Test refactoring with new methods
Excluded Thread.sleep
> TC_01.006.16

- src/test/java/school/redrover/Header2Test.java
https://trello.com/c/AJdWfMdN/824-tc1400202-headersearch-box-verify-partial-match-search-functionality-for-an-existing-entity
> TC_14.002.02 | Header > Search box > Verify partial match search functionality for existing entities

- src/test/java/school/redrover/ViewTest.java
> TC_10.001.08 create new empty view

- src/test/java/school/redrover/DeleteProjectTest.java
> refactoring DeleteProjectTest

- src/test/java/school/redrover/Folder3Test.java
https://trello.com/c/RzEkXBbY/834-rf0400109-folder-refactoring
> TC_00.005.22 | refactoring dependency

- src/test/java/school/redrover/Folder10Test.java
https://trello.com/c/yHBpd6cs/846-tc0400113-folder-rename-folder
> TC_04.001.13 folder rename test after folder create

- src/test/java/school/redrover/User4Test.java
- src/test/java/school/redrover/User5Test.java
https://trello.com/c/swjAw9WB/851-tc1300111-user-create-user-verify-that-users-with-same-username-cant-be-created
> TC_13.001.11 | User > Create User > Verify that users with same Username can't be created

- src/test/java/school/redrover/FreestyleProjectSeTest.java
TC_01.006.25 | Freestyle project > Configure General settings > Verify Value Of Inserted Git Source Link
https://trello.com/c/Q71iZYbN/849-tc01006025-freestyle-project-configure-general-settings
> TC_01.006.25 | Freestyle project > Configure General settings > Verify Value Of Inserted Git Source Link

- src/test/java/school/redrover/User4Test.java
https://trello.com/c/eeFHTXuC/853-tc1300112-user-create-user-verify-validation-if-password-and-confirm-password-didnt-match
> TC_13.001.12 | User > Create User > Verify validation if Password and Confirm Password didn't match

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/jQOowanM/848-tc0101502-freestyle-project-move-project-move-project-to-folder
> TC_01.015.02 | Freestyle project > Move Project > Move project to folder

- src/test/java/school/redrover/User4Test.java
> TC_13.005.05 | User > Delete user > Verify logged-in user cannot be deleted

- src/test/java/school/redrover/NodeTest.java
https://trello.com/c/1qnEfogG/850-tc1500509-nodes-configure-node-see-a-warning-message
> TC_15.005.09 add testCheckWarningMessage

- src/test/java/school/redrover/Pipeline26Test.java
> TC_02.005.04 | Pipeline> Add Test Delete

- src/test/java/school/redrover/NodesTest.java
https://trello.com/c/1WHbpdU8/856-tc1500404-nodes-node-status-update-offline-reason
> TC_15.004.04 | Nodes > Node status > Update offline reason

- src/test/java/school/redrover/Folder17Test.java
https://trello.com/c/jAIjUAyP/852-tc0400208-folder-move-folder-to-folder
> dk/TC 04.002.08 move folder to folder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/B5W9iVuV/840-rf0000120-rf0100211-dependencies-of-tests
> RF_00.001.20 | RF_01.002.11 | Dependencies of tests and waits added

- src/test/java/school/redrover/FreestyleProjectSeTest.java
https://trello.com/c/RgcZOXub/790-tc01006007-freestyle-project-configure-general-settings-days-to-keep-builds-the-set-number-days-to-keep-builds-is-saved
> TC_01.006.007 |The set number Days to keep builds is saved.

- src/test/java/school/redrover/BreadCrumb6Test.java
- src/test/java/school/redrover/BreadCrumbTest6.java
https://trello.com/c/Imse818b/228-tc1100206-breadcrumb-return-on-main-page-from-any-page-by-click-dashboard
> TC_11.002.06

- src/test/java/school/redrover/Header2Test.java
https://trello.com/c/NnZaXsgM/825-tc1400203-header-search-box-verify-redirection-to-the-status-page-of-the-item-selected-from-the-search-results-list?filter=member:evgeniysleznik
> TC_14.002.03 | Header > Search box > Verify redirection to the status page of the item selected from the search results list

- src/test/java/school/redrover/Footer5Test.java
- src/test/java/school/redrover/Plugins1Test.java
https://trello.com/c/ppVeikei/555-tc1200404-footer-rest-api-link-redirection-from-main-menu-pages
> TC_12.004.04 Footer > REST API link > Redirection from Main Menu pages

- src/test/java/school/redrover/Header2Test.java
https://trello.com/c/76lDzOJd/826-tc1400204-header-search-box-verify-cursor-relocation-to-search-field-on-ctrlk-shortcut-activation
> TC_14.002.04 | Verify cursor relocation to "Search" field on Ctrl+K shortcut activation

- src/test/java/school/redrover/Pipeline26Test.java
> RF_02.005.04 | Pipeline> Add dependencies

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/NLbokgBv/812-tc0500212-multibranch-pipeline-rename-multibranch-pipeline-using-dropdown-in-the-breadcrumb?filter=RF
> Karatnat/TC_05.002.12 | Multibranch pipeline > Rename Multibranch pipeline using dropdown in the breadcrumb

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/3eo9VOyY/866-rf0100602-freestyle-project-configure-general-settings-combine-freestyleprojecttest-freestyleprojectsetest
> RF_01.006.03 | Freestyle project > Configure General settings - combine FreestyleProjectTest & FreestyleProjectSeTest

- src/test/java/school/redrover/FreestyleProjectTest.java
changed tests
TC_01.006.006 | TC_01.006.25
testDaysToKeepBuildsErrorMessageIsDisplayed
testVerifyValueOfInsertedGitSourceLink
https://trello.com/c/cemEK5I0/870-rf0100604-freestyle-project-configure-general-settings-verify-value-of-inserted-git-source-link
> RF_01.006.04 | Freestyle project > Configure General settings > Refactoring

- src/test/java/school/redrover/FreestyleProjectSeTest.java
Added 1 test to rename a freestyle project on the dashboard
https://trello.com/c/03Zn36tz/845-tc0100218-freestyle-project-rename-project-valid-title
> TC_01.002.18 | Freestyle project > Rename project > Valid title

- src/test/java/school/redrover/Pipeline13Test.java
https://trello.com/c/DSymXke4/354-tc0000213-creating-new-item-creating-pipelinecheck-creating-pipeline-project-with-a-valid-letter-name-via-new-item-button
https://trello.com/c/kXbBr82G/410-tc0200711-pipeline-rename-projectcheck-renaming-the-project-on-the-drop-down-menu-near-the-project-name-on-the-dashboard
> Refactoring of tasks TC_02.007.11 and TC_00.002.13

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/yUXxF5e7/858-tc01006008-freestyle-project-configure-general-settings-days-to-keep-builds-the-saved-notification-is-displayed
> TC_01.006.008 |The 'Saved' notification is displayed

- src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/fUlgeGjz/888-rf0600101-organization-folder-added-tests-to-the-organizationfoldertest
> RF_06.001.02

- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/NewItemPage.java
https://trello.com/c/TI8LqJ1i/901-rf0000506-new-item-organization-folder
> RF_00.005.06 | New Item > Organization Folder

- src/test/java/school/redrover/Footer3Test.java
- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/NewItemPage.java
- src/test/java/school/redrover/model/OrganizationFolderConfigurationPage.java
https://trello.com/c/Ne4nk9LZ/904-rf0000507-new-item-organization-folder
PS: вторым и третьим коммитом заигнорил упавшие на CI тесты:
> RF_00.005.07 | New Item > Organization Folder

- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/MyViewPage.java
- src/test/java/school/redrover/model/NewViewConfigurePage.java
- src/test/java/school/redrover/model/NewViewPage.java
> TC_10.001 | 09 Views > Create new view(POM)

- src/test/java/school/redrover/UserTest.java
> TC_13.001.13 | User > Create User > Verify User can log out

- src/test/java/school/redrover/Folder3Test.java
- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderGeneralConfigurationPage.java
- src/test/java/school/redrover/model/NewItemPage.java
https://trello.com/c/xhpkGnH8/909-rfaddcreatefolderpom
> RE/ RF_ 04.000.03_Folder > add Create Folder POM

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/DsKmjzPR
Remove thread sleep
> RF_01.010.02 | Freestyle project > Configure Build Environment settings > Add timestamps to the Console Output

- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/M7sG2tEl/910-rf1000107-views-create-new-view
> RF_10.001.07 Views > Create new view_without_jobs(pom)

- src/test/java/school/redrover/UserTest.java
> TC_13.001.15 | User > Create User > Verify that after user creation system navigates to 'Jenkins’ own user database' screen

- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/GlobalViewConfigPage.java
- src/test/java/school/redrover/model/GlobalViewPage.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/L5MEjL3k/919-rf1000211-views-edit-view-rename-view-pom
> RF_10.002.11 Change testRenameView using POM

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/UserPage.java
testUserIsDisplayedInUsersTable()
testUserRecordContainUserIdButton(), 
old methods and locators moved to the UserPage class
> POM, 2 tests have been refactored in the UserTest class:

- src/test/java/school/redrover/SystemLogTest.java
Refactoring SystemLogTest:
- remove not using method;
- optimisation testDeleteCustomLogRecorder for quickly execute;
> https://trello.com/c/0XFVqr1Y/929-rf0900702-manage-jenkins-system-log-delete-a-custom-log-recorder

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/xdLC4WBX/932-rf0400003-grooming-foldertest
> RF_04.000.03 Grooming FolderTest

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderConfigurationPage.java
- src/test/java/school/redrover/model/NewItemPage.java
https://trello.com/c/l41GGbZg/935-rf0400003-refactoring-pom
Rename FolderGeneralConfigurationPage; → FolderConfigurationPage;
Refactoring public NewItemPage selectItemFolder() (POM)
> RF_04.000.04 Refactoring POM

- src/test/java/school/redrover/FolderTest.java
> RF_04.006.01.02 | Folder>Configuration>General settings>Add Display

- src/test/java/school/redrover/FolderTest.java
[https://trello.com/c/Wk0Srv3d/937-rf0400504-folder-add-and-edit-description-ref](https://trello.com/c/Wk0Srv3d/937-rf0400504-folder-add-and-edit-description-ref)
> RF_04.005.04 | Folder > Add and edit description Refactoring

- src/test/java/school/redrover/BuildHistoryTest.java
- src/test/java/school/redrover/FreestyleProject10Test.java
- src/test/java/school/redrover/model/BuildHistoryPage.java
https://trello.com/c/WUBvwGge/938-rf0800104-build-history-view-the-build-history-tooltip-is-visible-in-the-time-since-section
> RF_08.001.04 | Build history > View the build history > Tooltip is visible in the "Time Since" section

- src/test/java/school/redrover/UserTest.java
> TC_13.003.11 | User > Configure User > Verify description could be added for the user from the "People" page

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/ConfigurationPage.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
> RF_04.006.01 | Folder > Add Display Name to POM

- src/test/java/school/redrover/UserTest.java
> TC_13.003.08 | User > Configure user > Verify description could be added for the user from the "Jenkins’ own user database" page

- src/test/java/school/redrover/UserTest.java
> TC_13.003.09 | User > Configure user > Verify description could be added for the active user using direct link in Header

- src/test/java/school/redrover/UserTest.java
> TC_13.003.12 | User > Configure user > User can show the preview of the description

- src/test/java/school/redrover/UserTest.java
https://trello.com/c/EBkvBrcc/821-tc1300105-user-create-user-full-name-field-is-automatically-populated-with-the-username-when-left-empty
> TC_13.001.05 | User > Create User > Full name field is automatically populated with the username when left empty

- src/test/java/school/redrover/PluginsTest.java
https://trello.com/c/7QY6IIMQ/759-tc0900101-manage-jenkins-plugins-installed-plugins-verify-installed-plugins-contain-ant
> Refactoring | Updated PluginsTest

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FolderConfigurationPage.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
Trello card: https://trello.com/c/YLVuRlvd/956-tc0400509-folderadd-descriptioncheck-preview
Test in POM added. What is tested: description in the description field and in the preview field match.
Some tests, which fail in CI, is ignored.
> TC_04.005.09 new branch

- src/test/java/school/redrover/MulticonfigurationProjectTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/MultiConfigurationConfigurePage.java
- src/test/java/school/redrover/model/MultiConfigurationDetailsPage.java
RF_03.000.04 | Multiconfiguration project > Refactoring Test for POM > 2
> RF_03.000.04 | Multiconfiguration project > Refactoring Test for POM > 2

- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/model/NodeCreatePage.java
> RF_15.001.04 | RF testCreateNewNodeCopyingExistingWithNotExistingName

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/BreadcrumbPage.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/WorkspacePage.java
- src/test/java/school/redrover/runner/TestUtils.java
> RF_01.014.03 | Freestyle project > refactoring to POM testIsWorkspaceCreated()

- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/OrganizationFolderConfigurationPage.java
- src/test/java/school/redrover/model/OrganizationFolderRenamePage.java
https://trello.com/c/9Z72kTSm/970-rf0000000-item-sub-item-us-title
> RF | Organization Folder > Converting to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/FreestyleProjectRenamePage.java
- src/test/java/school/redrover/model/HomePage.java
Refactored testRenameProjectFromDashboard to POM
https://trello.com/c/sHXL8Uq6/966-rf0100218-freestyle-project-rename-project
> RF_01.002.18

- src/test/java/school/redrover/CustomConfigureLogTest.java
https://trello.com/c/5gOZLlib/893-tc0900601-manage-jenkins-system-log-configure-a-custom-log-recorder-add-new-logger
> TC_09.006.01 | Manage Jenkins >System log >Configure a custom log recorder Add new Logger

- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/OrganizationFolderConfigurationPage.java
- src/test/java/school/redrover/model/OrganizationFolderDetailsPage.java
- src/test/java/school/redrover/model/OrganizationFolderRenamePage.java
https://trello.com/c/hUBnOJcV/973-rf0000000-item-sub-item-us-title
> RF | OrganizationFolder_POM

- src/test/java/school/redrover/SystemLogTest.java
Refactoring SystemLogTest:
- optimisation testDeleteCustomLogRecorder for delete ALL custom log recorders, located before and after of the default system log!
https://trello.com/c/1CkISmdG/981-rf0900703-manage-jenkins-system-log-delete-a-custom-log-recorder
> RF_09.007.03 | optimisation testDeleteCustomLogRecorder

- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/SystemLogTest.java
- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/GlobalViewPage.java
https://trello.com/c/fBrBZh2F/977-rf1000203-views-edit-view-refactor-existed-tests-to-pom
> RF_10.002.03 | Views > Edit view > Refactor existed tests to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
https://trello.com/c/gC9xD5po/984-tc0100109-freestyleproject-edit-the-existing-description
> added RF_01.001.09 in POM

- src/test/java/school/redrover/SystemLogTest.java
Refactoring SystemLogTest:
- the first test will  delete ALL custom log recorders
https://trello.com/c/rHKQ06yE/987-rf0900704-manage-jenkins-system-log-delete-a-custom-log-recorder
> RF_09.007.04 | first test will  delete ALL custom log recorders

- src/test/java/school/redrover/FreestyleProjectTest.java
testRenameProject was refactored to POM
https://trello.com/c/3a4mcw10/989-rf0100203-freestyle-project-rename-project-using-valid-name
> RF_01.002.03

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/tSziVByx/990-rf0000122-creating-new-item-creating-freestyle-project-with-valid-name
> RF_00.001.22|testCreateFreestyleProjectWithValidName

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
https://trello.com/c/rRrl81zF/993-rf0100622-freestyle-project-configure-general-settings-github-edited-label-appears-refactored-to-pom
> RF_01.006.22 | Freestyle project > Configure General settings > GitHub > Edited label appears - refactored to POM

- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/OrganizationFolderDetailsPage.java
https://trello.com/c/r4GZg4ii/986-rf0000000-item-sub-item-us-title
> RF | POM and removing Ignores

- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/GlobalViewPage.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/ListViewPage.java
https://trello.com/c/TlEEWw2l/994-rf1000204-views-edit-view-additional-refactoring-for-the-previous-refactoring-based-on-the-latest-java-lecture
> RF_10.002.04 | Views > Edit view > Additional refactoring for the previous refactoring based on the latest Java lecture

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
https://trello.com/c/FDQvwyJo/996-rf0100102-freestyleproject-add-description
> RF_01.001.02 | FreestyleProject > Add description to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
https://trello.com/c/2fWhoCE7/998-rf0100103-freestyleproject-add-description
> RF_01.001.03 | FreestyleProject > Add description from FreestyleProjectDetailsPage | to POM

- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/model/MultibranchPipelineDetailsPage.java
- src/test/java/school/redrover/runner/TestUtils.java
https://trello.com/c/w8Ls1Q5C
refactoring to POM
> RF_05.001.01 | MultibranchPipelineTest > testSidebarMenuConsistingOfTenTasks() > refactoring to POM

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/gD9by8A6
refactoring to POM
> RF_05.001.03 | MultibranchPipelineTest > testVisibilityOfTasksOnSidebarMenu() > refactoring to POM

- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/ErrorPage.java
- src/test/java/school/redrover/model/NewItemPage.java
https://trello.com/c/jhhMiSbY/1001-rf0000508-new-item-organization-folder
> RF_00.005.08 | New Item > Organization Folder

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/L85Ks2ZI/1004-rf0100702-freestyle-project-configure-advanced-settings-visibility-of-help-description-quiet-period
> Ab/rf 01.007.02

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- testEditDescription is refactored to POM
- FreestyleProjectDetailsPage - new method deleteDescriptionText was created
https://trello.com/c/pvTGnFA1/1005-rf0100104-freestyleproject-add-description-from-freestyleprojectdetailspage
> RF_01.001.04 | FreestyleProject > Edit description from FreestyleProjectDetailsPage

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
https://trello.com/c/uQPnBx6f/991-rf0100603-pom-freestyle-project-this-project-is-parameterized-checkbox-ticked
> RF_01.006.03 | POM | Freestyle project > This project is parameterized checkbox ticked

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectRenamePage.java
https://trello.com/c/GpTmz55M/995-rf0100202-freestyle-project-rename-project-entering-unsafe-characters-refactoring-to-pom
> RF_01.002.02 | Freestyle project > Rename project > Entering unsafe characters > Refactoring to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
https://trello.com/c/gbko7QcI/1000-rf0100305-pom-reestyle-project-delete-existing-project-from-side-menu-on-project-status-page
> RF_01.003.05 | POM | Freestyle project > Delete existing project from side menu on Project Status page

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/k0xRSnjX/1008-rf0000120-pom-creating-new-item-creating-freestyle-project-from-existing-freestyle-project
> RF_00.001.20 | RF_01.002.11 | tests removed as duplicates

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/wjOghyNS/1011-rf00002-creating-new-item-creating-pipeline-testcreatewithemptyname-to-pom
> RF pipeline testCreateWithEmptyName to POM

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/NewItemPage.java
- src/test/java/school/redrover/model/NewJobPage.java
[TC_00.002.16 | Creating new item >Creating Pipeline](https://trello.com/c/5FHvm21L/1009-tc000002021-creating-new-item-creating-pipeline)
> pipeline page, testCreatePipeline

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/ListViewConfigurationPage.java
- src/test/java/school/redrover/model/ListViewPage.java
- src/test/java/school/redrover/model/NewViewConfigurePage.java
https://trello.com/c/UAo4i8Ds/1010-rf1000205-views-edit-view-refactor-existed-tests-to-pom
> RF_10.002.05 | Views > Edit view > Refactor existed tests to POM

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/NewItemPage.java
- src/test/java/school/redrover/model/PipelinePage.java
- src/test/java/school/redrover/model/PipelineRenamePage.java
https://trello.com/c/EaBgbNLK/1012-rf02007-pipeline-rename-project-testpipelinerename-to-pom
> RF testPipelineRename to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/FreestyleProjectRenamePage.java
- src/test/java/school/redrover/model/RenameErrorPage.java
Freestyle project > Rename project existing project
testRenameToEmptyName is refactored to POM
RenameErrorPage class is added
https://trello.com/c/6dMAB8t1/1017-rf0100204-freestyle-project-rename-project-existing-project
> TC_01.002.04

- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/model/NodeCreatePage.java
https://trello.com/c/nJN4ZSaU/1016-tc1500116-nodes-create-new-node-try-creating-a-node-without-an-permanent-agent
> TC_15.001.16 | Nodes > Create new node > Try creating a node without "Permanent Agent"

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
https://trello.com/c/L85Ks2ZI/1004-rf0100702-freestyle-project-configure-advanced-settings-visibility-of-help-description-quiet-period
> RF_01.007.02

- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/model/NodeCofigurationPage.java
- src/test/java/school/redrover/model/NodeDetailsPage.java
https://trello.com/c/yX4dziYx/1019-rf1500502-nodes-ref-nodetest-class
> RF_15.005.02 testAddDescription and testSetIncorrectNumberOfExecutes to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
- testDeleteTheExistingDescription is refactored to POM
https://trello.com/c/H9JkqmCJ/1025-rf0100105-freestyleproject-delete-description-from-freestyleprojectdetailspage
> RF_01.001.05 | FreestyleProject > Delete description from FreestyleProjectDetailsPage

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/model/MultibranchPipelineDetailsPage.java
- src/test/java/school/redrover/model/MultibranchPipelineRenamePage.java
- src/test/java/school/redrover/model/UserDatabasePage.java
https://trello.com/c/yieKWSIV
https://trello.com/c/kdBZCkRh
https://trello.com/c/b6C7ypTe
https://trello.com/c/2SlzsHLU
> refactoringPOM

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/PipelinePage.java
https://trello.com/c/hH4gMYe4/1027-rf02003-pipeline-build-now-testverifybuildiconondashboard
RF PipelineTest testVerifyBuildIconOnDashboard to POM
add clickBuildNow()
isBuildIconDisplayed()
use TestUtils for create pipeline project
private method clickBuildNow() was moved to the PipelinePage, dependent tests are refactored
> RF_02.003| Pipeline > Build Now > testVerifyBuildIconOnDashboard to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/zrdsmKLo/1007-rf0101601-pom-dependency-freestyle-project-navigate-to-status-project-page-by-clicking-on-the-project-name-on-home-page
> RF_01.016.01 | POM | Dependency | Freestyle project > Navigate to Status project page by clicking on the project name on home page

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
https://trello.com/c/vAorMAgN/1018-rf0100602-pom-freestyle-project-configure-general-settings-this-project-is-parameterized-checkbox-selected
> RF_01.006.02 POM | Freestyle project > Configure General settings > This project is parameterized checkbox selected

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/OrganizationFolderDetailsPage.java
- src/test/java/school/redrover/model/base/BaseProjectPage.java
https://trello.com/c/tm840yWQ/1002-rf0000000-item-sub-item-us-title
> RF | POM adding BaseProjectPage

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
https://trello.com/c/qXtKk6we/1037-rf0100621-freestyle-project-configure-general-settings-add-build-step
Freestyle project > Configure General settings > Add build step
testAddBuildStep was refactored to POM
Respective methods were added in FreestyleProjectConfigurePage
> RF_01.006.21

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/model/ManageJenkinsPage.java
- src/test/java/school/redrover/model/PluginsPage.java
https://trello.com/c/7QY6IIMQ/759-tc0900101-manage-jenkins-plugins-installed-plugins-verify-installed-plugins-contain-ant
> Refactor TC_09.001.01 | Manage Jenkins > Plugins > Installed Plugins > Verify Installed Plugins contain Ant

- src/test/java/school/redrover/SystemLogTest.java
Begin to refactoring to POM:
refactoring method “openSyslogPage"
https://trello.com/c/D960C4ld/1039-rf0900501-manage-jenkins-system-log-create-a-custom-log-recorder
> RF_09.005.01

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/4erjiIEL/654-tc0101602-freestyle-project-verify-7-task-links-in-the-side-panel-status-changes-workspace-build-now-configure-delete-project-re
> TC_01.016.02 | Freestyle project > Verify 7 task links in the side panel: Status, Changes, Workspace, Build Now, Configure, Delete Project, Rename

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/NewItemTest.java
- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/AngryErrorPage.java
- src/test/java/school/redrover/model/ErrorPage.java
- src/test/java/school/redrover/model/FreestyleProjectRenamePage.java
- src/test/java/school/redrover/model/NewItemPage.java
- src/test/java/school/redrover/model/NodeCofigurationPage.java
- src/test/java/school/redrover/model/base/BaseErrorPage.java
https://trello.com/c/hg6yDmzi/1028-rf1500503-nodes-ref-nodetest-class
> Move to POM - testSetEnormousNumberOfExecutes

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/gC9xD5po/984-rf0100109-freestyleproject-edit-the-existing-description-refactor-existed-tests-to-pom
> Modified test RF_01.001.09, added dependsOnMethods method.

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/zrdsmKLo/1007-rf0101601-pom-dependency-freestyle-project-navigate-to-details-project-page-by-clicking-on-the-project-name-on-home-page
> RF_01.016.01 | POM | Dependency | Freestyle project > Navigate to Details project page by clicking on the project name on home page

- src/test/java/school/redrover/FreestyleProjectTest.java
Freestyle project > Configure General settings > Days to keep builds> The set number Days to keep builds is saved
https://trello.com/c/R3JBcl3A/1042-rf01006007-freestyle-project-configure-general-settings-days-to-keep-builds-the-set-number-days-to-keep-builds-is-saved
testSetNumberDaysToKeepBuildsIsSaved was refactored to POM
> RF_01.006.007

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/KfrN22iD/142-tc1200103-footer-jenkins-version-viewing-the-jenkins-version
new Trello card
https://trello.com/c/R3dFo2ZM/1054-tc1200113-footer-jenkins-version-viewing-the-jenkins-version
> refactoring test testVersionJenkins

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
> RF_01.014.03 | Freestyle project > refactoring testIsWorkspaceCreated() and methods 

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderConfigurationPage.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
- src/test/java/school/redrover/model/NewItemPage.java
https://trello.com/c/A2oYuXL1/611-tc0400701-folder-configuration-health-metrics-settings-add-child-health-metrics
> TC_04.007.01 | Folder > Configuration > Health metrics settings > Add Child Health Metrics

- src/test/java/school/redrover/model/base/BaseErrorPage.java
https://trello.com/c/aVzWKj1k/1050-rf0150504-change-heritage
> Changed heritage BaseErrorPage from BasePage

- src/test/java/school/redrover/SystemLogTest.java
- src/test/java/school/redrover/model/ConfigureLogRecorderPage.java
- src/test/java/school/redrover/model/SystemLogPage.java
Refactoring testCreateCustomLogRecorder to POM
https://trello.com/c/JjDhONq5/1057-rf0900502-manage-jenkins-system-log-create-a-custom-log-recorder
> RF_09.005.02 testCreateCustomLogRecorder

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/CreatedUserPage.java
- src/test/java/school/redrover/model/PeoplePage.java
Refactoring in POM
https://trello.com/c/Sloy6cYB
> RF_13.003.05 | User > Configure user > Add user description

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
- src/test/java/school/redrover/model/NodesListPage.java
https://trello.com/c/bhAtk9uK/1059-rf01006002-freestyle-project-configure-general-settings-the-help-description-of-discard-old-builds-is-visible
> RF_01.006.002 |Freestyle project > Configure General settings >The help description of 'Discard old builds' is visible.(POM)

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
https://trello.com/c/fxXFezX4/1043-rf0100614-freestyleproject-configure-general-settings-select-this-project-is-parameterized-checkbox-add-boolean-parameter
testThisProjectIsParameterizedCheckboxAddBooleanParameter was refactored to POM
respective methods were added in FreestyleProjectConfigurePage
> RF_01.006.14

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/zrdsmKLo/1007-rf0101601-pom-dependency-freestyle-project-navigate-to-details-project-page-by-clicking-on-the-project-name-on-home-page?filter=member:ekaterina_sokolova_v
> RF_01.016.01 | getWait10 added in clickOnJob()

- src/test/java/school/redrover/BuildHistoryTest.java
- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/model/BuildHistoryPage.java
https://trello.com/c/nbbnqgi2/1038-tc0800106-build-history-view-the-build-history-return-build-point
and refactoring some my methods
> TC_08.001.06 | Build history > View the build history > Return build point

- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/model/ManageJenkinsPage.java
- src/test/java/school/redrover/model/PluginsPage.java
https://trello.com/c/hugnbVhE/1066-rf09001-item-sub-item-us-title
> Refactor POM plugin test

- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/model/NodeCofigurationPage.java
- src/test/java/school/redrover/model/NodeDetailsPage.java
https://trello.com/c/s4dkikY7/1070-rf1500505-nodes-ref-nodetest-class
> Changed to POM testAddLabel and testCheckWarningMessage

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
- src/test/java/school/redrover/model/FolderMovePage.java
https://trello.com/c/Hiq6q9WK/1069-rf0400205-refactoring-to-pom
> RF_04.002.05 |  Refactoring to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/RUYv2xPr/1080-rf0000111-creating-new-item-creating-freestyle-project-with-empty-name
> Refactor pom method

- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/MyViewPage.java
https://trello.com/c/ZzWCF2Z3/1091-rf000000-item-sub-item-us-title
> RF_10.001.06 From My View Page > Creating new folder > POM

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/5VtVdriz
RF_002.000 | Delete tests duplicates and refactor methods use in Pipeline class
> RF_002.000 | Pipeline > Delete tests duplicates and refactor methods use to TestUtils use

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/PipelineDetailsPage.java
- src/test/java/school/redrover/model/ReplayBuildPipelinePage.java
https://trello.com/c/EB7b7Zk0/1076-tc02003-pipeline-build-now-replay-build
Add  testReplayBuildPipeline.
Add to the PipelineDetailsPage methods: getLastBuildLinkText()
clickReplaySideMenu()
clickLastBuildLink().
Add new page ReplayBuildPipelinePage
> TC__02.003 | Pipeline > Build now > Replay Build

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
- src/test/java/school/redrover/model/PipelineDetailsPage.java
-testDeletePipelineInsideOfFolder is refactored to POM
https://trello.com/c/IqB2dWU0/1077-rf0400308-folder-create-a-new-job-inside-a-folder-create-pipeline-and-verify-deletion-of-pipeline
> RF_04.003.08 | Folder > Create a new job inside a folder > Create Pipeline and verify deletion of Pipeline

- src/test/java/school/redrover/SystemLogTest.java
- src/test/java/school/redrover/runner/TestUtils.java
Add clearAllCustomLogRecorders to TestUtils
Refactoring: add precondition to the  testCreateCustomLogRecorder
https://trello.com/c/NwqNhMtX/1092-tc0900501-manage-jenkins-system-log-create-a-custom-log-recorder
> RF_09.005.02 RF_09.005.02 Add clearAllCustomLogRecorders to TestUtils & Refactoring: add precondition to the  testCreateCustomLogRecorder

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/LVyprriQ/1094-refactoring
> RF_01.004.11

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
https://trello.com/c/pR9IZa8Y/1098-rf-dependsonmethods-testtooltipdiscardoldbuildsisvisible
> RF _01.006.003 |The help description of 'Discard old builds' is closed after click again.(POM)

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderConfigurationPage.java
https://trello.com/c/RmnlcF5m/1087-tc0400702-folder-configuration-health-metrics-settings-displaying-help-text-button-recursive
> TC_04.007.02 | Folder > Configuration Health metrics settings > Displaying help text button "Recursive"

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/PipelineDetailsPage.java
RF _02.00.000 | PipelineTest > testPermalinksIsEmpty, testDelete to POM
> RF _02.00.000 | PipelineTest > testPermalinksIsEmpty, testDelete to POM

- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/model/BuildInNodeConfigurationPage.java
- src/test/java/school/redrover/model/BuiltInNodeDetailPage.java
- src/test/java/school/redrover/model/NodeDetailsPage.java
https://trello.com/c/dfnIPz2a/1099-rf-1500506-nodes-ref-nodetest-class
> testSetCorrectNumberOfExecutorsForBuiltInNode changed to POM

- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/model/BuiltInNodeConfigurationPage.java
https://trello.com/c/QypAi1xE/1105-rf1505007-item-sub-item-us-title
> testRenameWithIncorrectName changed to POM

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/base/BasePage.java
> TC_05.001.06 | Multibranch pipeline > View Multibranch pipeline page >Verify the user can find job by quick search

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
- src/test/java/school/redrover/model/FolderMovePage.java
https://trello.com/c/mRycvbaO/1106-rf-04002051-anotation-findby
> RF_04.002.051 |  Refactoring @FindBy

- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/model/MultibranchPipelineConfigurationPage.java
- src/test/java/school/redrover/model/NewItemPage.java
https://trello.com/c/sHNaxhzR/1097-rf0000604-create-multibranch-pipeline-from-non-existing-multibranch-pipeline
> testMultibranchCreationFrom NonExisting refactoring to POM

- src/test/java/school/redrover/model/OrganizationFolderDetailsPage.java
> refactoring clickDelete

- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/OrganizationFolderConfigurationPage.java
- src/test/java/school/redrover/model/OrganizationFolderDetailsPage.java
- src/test/java/school/redrover/model/OrganizationFolderRenamePage.java
https://trello.com/c/didYLkZH/1110-rf0600001-organization-folder
> RF_06.000.01 | Organization folder > Refactoring to POM

- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/model/NodesListPage.java
https://trello.com/c/hbj3g06O/1109-rf1501009-nodes-ref-nodeclass
> rewrote testSortNodesInReverseOrder to POM.

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
Folder > Add and edit description > Edit description
testEditDescriptionOfFolder was refactored to POM
addOrEditDescription was renamed to be in accordance with button actual title
testEditDescriptionOfFolder was refactored to POM
addOrEditDescription was renamed to be in accordance with button actual title
https://trello.com/c/kBLU4XC3/1116-tc00007-creating-new-item-folder-item-verify-folder-is-not-created-with-empty-foldername
> RF_04.005.02/2

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/CreateNewUserPage.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/UserDatabasePage.java
https://trello.com/c/6MZoMgLC/1114-rf1300102-user-refactor-user-tests-to-pom
> Refactor user test

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/RrF1Ig8p/1119-rf0000711-pom-creating-new-item-folder-item-verify-ok-button-is-not-clickable-without-folder-name
testOKButtonIsNotClickableWithoutFolderName was refactored to POM
> RF_00.007.11 | POM | Creating new item > Folder item >Verify OK Button Is Not Clickable Without Folder Name

- src/test/java/school/redrover/MultibranchPipelineTest.java
https://trello.com/c/oTQ64SOa/1125-rf0000002-multibranchpipelinetest-class
> Refactored MultibranchPipelineTest. Deleted Create Method

- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/ListViewConfigurationPage.java
- src/test/java/school/redrover/model/ListViewPage.java
https://trello.com/c/QNlmofW0/911-tc1000213-views-edit-view-view-can-be-renamedpom
> RF_10.001.07 Views > Create new view (pom)

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
[https://trello.com/c/UDEdoU83/1124-rf0400506-folder-add-and-edit-description-delete-description-pom](https://trello.com/c/UDEdoU83/1124-rf0400506-folder-add-and-edit-description-delete-description-pom)
Refactoring  to POM
> RF_04.005.06 | Folder > Add and edit description > Delete description >POM

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/NewItemPage.java
https://trello.com/c/9cXGvppd/1129-rf0100409-pom-freestyleproject-enable-or-disable-project-verify-there-is-no-schedule-a-build-button-for-disabled-project-on-home
testScheduleBuildButtonOnDashboardWhenDisabled was renamed to testScheduleBuildButtonNotVisibleWhenProjectDisabled and refactored to POM
method clickOk/NewItemPage was refactored
method refreshPage was refactored
method createPipelinePage/NewItemPage was renamed to createPipeline method createNewPipelineProject/NewItemPage deleted and replaced by createPipeline
method clickRenameLink/FreestyleProjectDetailsPage renamed to clickRename
method clickRenameItem/FreestyleProjectDetailsPage deleted and replaced by clickRename
testRenameToEmptyName renamed to testRenameToEmptyNameAndGoErrorPage
> RF_01.004.09 | POM | FreestyleProject > Enable or disable project> Verify there is no Schedule a Build Button for disabled project on home page

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
https://trello.com/c/TCio6iMp/1131-rf-0100610-pom-freestyle-project-configure-general-settings-discard-old-builds-settings-field-is-displayed
testSettingsOfDiscardOldBuildsIsDisplayed refactored to POM
disableToggle/FreestyleProjectConfigurePage renamed to disableEnableToggle clickDisableToggle/FreestyleProjectConfigurePage renamed to clickDisableEnableToggle
Were refactored:
testSelectThisProjectIsParameterizedCheckbox,
testVerifyValueOfInsertedGitSourceLink
Deleted due to duplication:
testFreestyleProjectConfigureGeneralSettingsThisProjectIsParameterizedCheckbox, testDisableFreestyleProjectFromFreestyleProjectDetailPage
testFreestyleProjectConfigureGeneralSettingsThisProjectIsParameterizedCheckboxSelected renamed to testFreestyleProjectConfigureIsParameterizedCheckboxSelected and …
> RF_01.006.10 | POM | Freestyle project > Configure General settings > Discard Old Builds > Settings field is displayed

- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/model/MultibranchPipelineConfigurationPage.java
- src/test/java/school/redrover/model/MultibranchPipelineDetailsPage.java
RF_05.005.01 | Multibranch Pipeline > Enable Multibranch Pipeline > Enable By Default
testEnabledByDefault was refactored to POM
https://trello.com/c/ENVXp8LF/1138-rf0500501-multibranch-pipeline-enable-multibranch-pipeline-enable-by-default
> RF_05.005.01

- src/test/java/school/redrover/SystemLogTest.java
- src/test/java/school/redrover/model/ConfigureLogRecorderPage.java
- src/test/java/school/redrover/model/LogRecordersDetailsPage.java
https://trello.com/c/zFKNhITU/1062-tc0900602-manage-jenkins-system-log-delete-the-all-existing-loggers-in-the-custom-log-recorder
> TC_09.006.02 | Manage Jenkins >System log >Delete the all existing loggers in the custom log recorder

- src/test/java/school/redrover/MultibranchPipelineTest.java
testCreateMultiConfigurationPipeline was refactored to POM
https://trello.com/c/waCkn2Wu/1142-rf0000214-creating-new-pipeline-project-with-valid-data
> RF_00.002.14 | Creating new pipeline project with valid data

- src/test/java/school/redrover/BreadcrumbTest.java
changing the number of indents in a class
> RF | Class BreadcrumbTest| changing the number of indents in a class

- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/OrganizationFolderRenamePage.java
- src/test/java/school/redrover/model/RenamePage.java
- src/test/java/school/redrover/model/base/BaseProjectPage.java
https://trello.com/c/bZu4RxCN/1132-rf-0000000-item-sub-item-us-title
> RF|RenamePage_generics

- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/model/ManageJenkinsPage.java
https://trello.com/c/oTexEI73/1144-tc0900809-view-manage-jenkins-page-clickability-clickability-of-troubleshooting-block-sections
> TC_09.008.09 |  Clickability of Troubleshooting block Sections

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/CreatedUserPage.java
- src/test/java/school/redrover/model/UserConfigurationPage.java
- src/test/java/school/redrover/model/UserCreateViewPage.java
- src/test/java/school/redrover/model/UserViewPage.java
[https://trello.com/c/HeCWkseQ/1136-rf1300307-user-configure-user-set-users-default-view](https://trello.com/c/HeCWkseQ/1136-rf1300307-user-configure-user-set-users-default-view)
-Refactor to POM
-Remove duplicated test
> RF_13.003.07 | User > Configure user > Set User's default view > POM

- src/test/java/school/redrover/ViewTest.java
- src/test/java/school/redrover/model/MyViewPage.java
- src/test/java/school/redrover/model/NewViewPage.java
https://trello.com/c/dr7sVqU4/1140-rf1000114-views-create-view-with-option-global-view-pom
> RF_10.001.14 | Views > Create view > With Option Global View > POM

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/HeaderTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/MulticonfigurationProjectTest.java
- src/test/java/school/redrover/model/AboutJenkinsPage.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/MultibranchPipelineConfigurationPage.java
- src/test/java/school/redrover/model/MultibranchPipelineDetailsPage.java
- src/test/java/school/redrover/model/RestAPIPage.java
- src/test/java/school/redrover/model/SearchResultQueryPage.java
- src/test/java/school/redrover/model/WebsiteJenkinsIOPage.java
- src/test/java/school/redrover/model/WorkspacePage.java
- src/test/java/school/redrover/model/base/BasePage.java
https://trello.com/c/JHtbxzO5/1139-rf1400001-header-refactoring-to-pom
> RF_14.000.01 | Header > Refactoring to POM

- src/test/java/school/redrover/NodesTest.java
- src/test/java/school/redrover/model/NodesListPage.java
https://trello.com/c/Xyi8C96G/1171-rf1501015-nodes-create-new-node-sees-node-in-table-of-nodes-sort-by-name-in-reverse-order
> RF_15.01.015 | Nodes > Create new node > Sees node in table of nodes > Sort by name in reverse order

- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/SystemLogTest.java
- src/test/java/school/redrover/model/ConfigureLogRecorderPage.java
- src/test/java/school/redrover/model/PluginsPage.java
https://trello.com/c/dXxh6eDp/1083-tc0900906-manage-jenkins-plugins-redirection-on-plugins-page
> Tc 09.009.06 redirection on plugins page

- src/test/java/school/redrover/UserTest.java
User > Create User > Verify that new user displayed on 'People' screen
https://trello.com/c/y4ju71jO/1176-tc1300117-user-create-user-verify-that-new-user-displayed-on-people-screen
> TC_13.001.17

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/LogInPage.java
[https://trello.com/c/pwIbidvc/1182-rf1300106-user-create-user-log-in-with-new-users-credentials](https://trello.com/c/pwIbidvc/1182-rf1300106-user-create-user-log-in-with-new-users-credentials)
refactor testCreateUserAndLogIn to POM
Не дублировала часть по созданию юзера, т.к. есть такой самостоятельный тест, сделала на него депенденси
> RF_13.001.06 | User > Create User > Log in with new user's credentials

- src/test/java/school/redrover/PipelineTest.java
> TC_02.001 | Pipeline >View pipeline page > Move Pipeline To Folder

- src/test/java/school/redrover/NodesTest.java
https://trello.com/c/dxOAE19E/1186-rf-1500508-nodes-ref-nodesclass
> testRenameWithIncorrectName and testCreateNewNodeWithInvalidNameFromMainPanel were rewritten with DataProvide

- src/test/java/school/redrover/BuiltInNodeDetailTest.java
- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/HeaderTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/AboutJenkinsPage.java
- src/test/java/school/redrover/model/BuildHistoryPage.java
- src/test/java/school/redrover/model/CreatedUserPage.java
- src/test/java/school/redrover/model/CredentialsPage.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/MyViewPage.java
- src/test/java/school/redrover/model/PeoplePage.java
- src/test/java/school/redrover/model/RestApiPage.java
- src/test/java/school/redrover/model/UserBuildPage.java
- src/test/java/school/redrover/model/UserConfigurationPage.java
- src/test/java/school/redrover/model/UserDatabasePage.java
- src/test/java/school/redrover/model/UserStatusPage.java
- src/test/java/school/redrover/model/WebsiteJenkinsPage.java
- src/test/java/school/redrover/model/base/BasePage.java
- src/test/java/school/redrover/model/base/BaseUserPage.java
https://trello.com/c/Clot5osI/1179-rf1200401-footer-rest-api-link-refactoring-to-pom
> RF_12.004.01 | Footer > REST API link > Refactoring to POM

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/UserDatabasePage.java
https://trello.com/c/EtHQ4txG/1190-tc1300105-user-create-user-full-name-field-is-automatically-populated-with-the-username-when-left-empty
> Test FullName Appears Same As UserId When Creating New User

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/LogInPage.java
- src/test/java/school/redrover/model/UserDatabasePage.java
refactoring of UserTest.java
https://trello.com/c/wFiiHRCZ/1188-rf-1300001-refactoring-of-the-usertest-class
> TC_13.001.17 refactoring

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/UserDatabasePage.java
-testCreateUser is refactored to POM
https://trello.com/c/FFi3OfPr/1198-rf1300101-pom-user-create-user-create-user-with-valid-name
> RF_13.001.01 | POM | User > Create User > Create User with valid name

- src/test/java/school/redrover/UserTest.java
testConfigureUser() was refactor to POM and rename to testAddUserDescriptionFromPeople()
https://trello.com/c/q7dxO05t/1199-rf1300304-user-configure-user
> RF_13.003.04 | User > Configure user

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/UserConfigurationPage.java
[https://trello.com/c/ft7wbN2R/1200-rf-1300300-user-deleted-duplicated-tests](https://trello.com/c/ft7wbN2R/1200-rf-1300300-user-deleted-duplicated-tests)
Refactor testConfigureShowDescriptionPreview to POM
Remove some tests which have duplicates in POM
> RF _13.003.00 | User > POM, deleted duplicated tests

- src/test/java/school/redrover/UserTest.java
https://trello.com/c/mZxSclgY/1203-rf1300117-user-create-user-create-user-with-invalid-name
> Refactor to POM User > Create User > Create User with invalid name

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/UserDatabasePage.java
https://trello.com/c/IXKa1JFt/1204-rf1300118-user-create-user-create-user-with-valid-name
> Refactor to POM User > Create User > Create User with valid name

- src/test/java/school/redrover/UserTest.java
TC_13.001.01 | User > Create User > Create User with valid name
https://trello.com/c/VIwWOvMW/1071-tc1300101-user-create-user-create-user-with-valid-name
> Add test with name testUser

- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/SystemLogTest.java
- src/test/java/school/redrover/model/PluginsPage.java
https://trello.com/c/f26xmqA2/1207-tc0900401-manage-jenkins-update-plugins-verify-the-update-button-is-not-clickable-by-default
> TC_09.004.01 | Manage Jenkins > Update Plugins > Verify the update button is not clickable by default

- src/test/java/school/redrover/UserTest.java
-testCreateUserWithInvalidName was added @DataProvider
https://trello.com/c/0riDFYMq/1213-rf1300117-2-user-create-user-create-user-with-invalid-name
> RF_13.001.17/2 | User > Create User > Create User with invalid name

- src/test/java/school/redrover/UserTest.java
testCreateUserWithInvalidCredentials with dataProvider
https://trello.com/c/HDnSZKB3/1214-tc13001-user-create-user-negative-data-usage
> TC_13.001.14 | User > Create User > With invalid credentials

- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/model/PluginsPage.java
TC_09.004.02 | Manage Jenkins > Update Plugins > Verify the update button is Enabled when any plugin is selected
> TC_09.004.02 | Manage Jenkins > Update Plugins > Verify the update button is Enabled when any plugin is selected

- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/model/PluginsPage.java
https://trello.com/c/fhbGSDTN/1210-tc0900403-manage-jenkins-update-plugins-verify-that-all-plugins-are-selected-for-update-by-clicking-on-the-checkbox-on-the-title
> 09.004.03 Select all the plugin updates from the Title of the table

- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/model/ManageJenkinsPage.java
- src/test/java/school/redrover/model/PluginsPage.java
https://trello.com/c/kCoDTHTj/1209-tc0900404-manage-jenkins-update-plugins-verify-that-the-number-on-the-plugins-section-on-the-manage-jenkins-page-matches-the-num
> TC_09.004.04 | Update Plugins > Verify that the number on the Plugins section matches the number of plugins on the Plugins page

- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/UserConfigurationPage.java
https://trello.com/c/IFwKE7PD/1219-rf-1300308-user-configure-user-testconfigureadddescriptionusingdirectlinkinheader-to-pom
RF testConfigureAddDescriptionUsingDirectLinkInHeader() to POM
> RF _13.003.08 | User > Configure user > testConfigureAddDescriptionUsingDirectLinkInHeader to POM

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/BuildEditInformationPage.java
- src/test/java/school/redrover/model/BuildPage.java
- src/test/java/school/redrover/model/PipelineDetailsPage.java
https://trello.com/c/1qGHMwZQ/1222-tc02003-pipeline-build-now-add-display-name-for-build
> TC_02.003 | Pipeline > Build now> Add Display Name For Build

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/MulticonfigurationProjectTest.java
- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/model/CredentialsPage.java
- src/test/java/school/redrover/model/FolderConfigurationPage.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
- src/test/java/school/redrover/model/FreestyleProjectConfigurePage.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/MultiConfigurationDetailsPage.java
- src/test/java/school/redrover/model/MultibranchPipelineDetailsPage.java
- src/test/java/school/redrover/model/OrganizationFolderDetailsPage.java
- src/test/java/school/redrover/model/PipelineConfigurePage.java
- src/test/java/school/redrover/model/PipelineDetailsPage.java
- src/test/java/school/redrover/model/base/BasePage.java
- src/test/java/school/redrover/model/base/BaseProjectPage.java
https://trello.com/c/u5M9XMbG/1220-rf-0000000-refactor-baseprojectpage
>  Refactor BaseProjectPage

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/MulticonfigurationProjectTest.java
- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/FolderConfigurationPage.java
- src/test/java/school/redrover/model/FolderDetailsPage.java
- src/test/java/school/redrover/model/FreestyleProjectDetailsPage.java
- src/test/java/school/redrover/model/MultiConfigurationDetailsPage.java
- src/test/java/school/redrover/model/PipelineDetailsPage.java
- src/test/java/school/redrover/model/base/BaseProjectPage.java
https://trello.com/c/5C4xEVG8/1226-rf-0000000-item-sub-item-us-title
> RF _00.00.000 | Refactoring FreestyleProjectDetailsPage> Move methods to BaseProjectPage >

- src/test/java/school/redrover/MulticonfigurationProjectTest.java
https://trello.com/c/pT7do2OX/1227-tc0000313-multiconfiguration-project-create-with-unvalid-name
> TC_00.003.13 | Multiconfiguration project >Create with unvalid name

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/BuildHistoryPage.java
- src/test/java/school/redrover/model/CreatedUserPage.java
- src/test/java/school/redrover/model/CredentialsPage.java
- src/test/java/school/redrover/model/HomePage.java
- src/test/java/school/redrover/model/MyViewPage.java
- src/test/java/school/redrover/model/PeoplePage.java
https://trello.com/c/Vd5R3inZ/1228-rf0101401-02-freestyle-project-item-view-permalinks-for-builds
RF_01.014.01/02 | POM | Freestyle project Item > View Permalinks for builds
testPermalinksListOnStatusPage() was refactored to POM
method getTextOfWebElements/MultibranchPipelineTest deleted due to no usage
testUserRecordContainUserIdButton, testDeleteUserAndLogIn were refactored
some Page models were refactored due to creation of method goApiRestPage in BasePage
testConfigureAddDescriptionFromPeoplePage, testDeleteUser3, testVerifyUserIdButton, testVerifyUserCreated, testLoginAsARemoteUser, testVerifyDisplayedUserAfterCreateUser, testNewUserDisplayedOnPeopleScreen deleted due to duplication
testUserRecordContainUserIdButton was renamed to testUserIdButtonIsClicableAfterUserCreation
> Rf 01.014.01/02

- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/model/PluginsPage.java
https://trello.com/c/AsC3IWqk/1230-tc0900405-manage-jenkins-update-plugins-sorting-plugin-updates-by-column-name-in-ascending-order-by-default
> TC_09.004.05 | Update Plugins > Sorting Updates by  Name in ascending order by default

- src/test/java/school/redrover/BuildHistoryTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/base/BaseDetailsPage.java
- src/test/java/school/redrover/model/builds/BuildPage.java
https://trello.com/c/ZTSCM8MM/1235-tc0800104-build-history-view-the-build-history-navigate-to-previous-build
testNavigationToPreviousBuild is created. Respective methods for test were added to BaseDetailsPage and BuildPage
> TC_08.001.04 | Build history > View the build history > Navigate to previous build

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/builds/BuildEditInformationPage.java
- src/test/java/school/redrover/model/builds/BuildPage.java
add testAddDescriptionForBuild()
https://trello.com/c/nmz2UsZZ/1239-tc02003-pipeline-build-now-add-description-for-build
> TC_02.003 | Pipeline > Build now > Add Description For Build

- src/test/java/school/redrover/PluginsTest.java
- src/test/java/school/redrover/model/PluginsPage.java
https://trello.com/c/g3K146n3/1240-tc0900406-manage-jenkins-update-plugins-sorting-plugins-updates-by-name-column-in-descending-order
> TC_09.004.06 | Manage Jenkins > Update Plugins > Sorting Plugins updates by Name column in descending order

- src/test/java/school/redrover/model/base/BaseViewPage.java
- src/test/java/school/redrover/model/view/MyViewsPage.java
- src/test/java/school/redrover/model/view/ViewPage.java
> add BaseViewPage

- src/test/java/school/redrover/BuildHistoryTest.java
- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/builds/BuildPage.java
-testVisibilityNavigationButtonsOnBuildPage was created
https://trello.com/c/MW4j8hv7/1243-tc0800106-build-history-view-the-build-history-navigate-to-previous-build
> TC_08.001.07 | Build history > View the build history > Visibility of Navigation Buttons On Build Page

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/model/HomePage.java
https://trello.com/c/YA3MRBNZ/1244-rf-1601007-freestyleprogect-configure-source-code-management-credentials
> Tc 16 001 01

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/model/CredentialsPage.java
- src/test/java/school/redrover/model/jobs/configs/FreestyleProjectConfigurePage.java
https://trello.com/c/I2SRWuCj/1211-rftc1600202-people-credentials-delete
> TC_16.002.02 changed assertion
